# Generated by tools/generate_models.py from neuroimaging-paper-parse.yaml.
# Do not edit: change the YAML and regenerate.
from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "1.12.0"
version = "0.6.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )





class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = None

class ArtifactKind(str, Enum):
    """
    Which of the two parse artifacts a header belongs to.
    """
    parsed_paper = "parsed_paper"
    """
    Contract C2, a ParsedPaper.
    """
    coordinate_parse = "coordinate_parse"
    """
    Contract C3, a CoordinateParse, original or revision.
    """


class DocumentSource(str, Enum):
    """
    Where the parsed text came from. Open vocabulary: a new source is added here when it is added to the download order, not discovered by a consumer.
    """
    pmc = "pmc"
    """
    PubMed Central OA web service.
    """
    europepmc = "europepmc"
    """
    Europe PMC full-text XML.
    """
    pubget = "pubget"
    """
    pubget's PMC download and parse.
    """
    elsevier = "elsevier"
    """
    Elsevier full-text API.
    """
    ace = "ace"
    """
    ACE HTML scraping.
    """
    pdf = "pdf"
    """
    A PDF converted to text.
    """


class SectionKind(str, Enum):
    """
    What a span of the text is.
    """
    title = "title"
    abstract = "abstract"
    introduction = "introduction"
    methods = "methods"
    results = "results"
    discussion = "discussion"
    figure_legend = "figure_legend"
    table = "table"
    """
    A table's rows, inlined into the text.
    """
    supplement = "supplement"
    references = "references"
    other = "other"


class MetaAnalysisBasis(str, Enum):
    """
    What `ParsedPaper.is_meta_analysis` was decided from.
    """
    publication_type = "publication_type"
    """
    A PubMed publication type such as Meta-Analysis or Systematic Review.
    """
    title = "title"
    """
    The title, when no publication type says so.
    """
    publication_type_and_title = "publication_type_and_title"
    """
    Both agree.
    """


class CoordinateOrigin(str, Enum):
    """
    Where a parsed analysis's points were read from.
    """
    table = "table"
    """
    Rows of a table in `ParsedPaper.tables`.
    """
    text = "text"
    """
    Sentences of the text, outside any table.
    """
    figure = "figure"
    """
    A result shown only in a figure, located by its legend or the sentence citing it. Its points are whatever the legend or the image states, often none.
    """


class ReportedSpace(str, Enum):
    """
    The coordinate space a point is in, normalized to the values NiMARE transforms between by `study_schema.spaces.normalize_space`. Absent when no space is stated, or when the wording names both MNI and TAL; never defaulted to MNI: a rat study stored as MNI is a wrong coordinate, and a missing one is an honest gap. What the paper printed stays in `space_as_printed`.
    """
    MNI = "MNI"
    """
    Any MNI template (MNI152, MNI305, ICBM152, SPM's MNI).
    """
    TAL = "TAL"
    """
    Talairach space, including Talairach-transformed MNI coordinates the paper reports as Talairach.
    """
    OTHER = "OTHER"
    """
    A stated space that is neither, such as a native, surface, or non-human template space.
    """


class SpaceBasis(str, Enum):
    """
    Where a space was read from, most specific first.
    """
    point = "point"
    """
    The row or sentence holding the point.
    """
    table_header = "table_header"
    caption = "caption"
    footer = "footer"
    methods = "methods"
    results = "results"
    extractor = "extractor"
    """
    The download source's own structured guess.
    """


class StatisticKind(str, Enum):
    """
    The kind of a value reported at a point. One vocabulary for the parse, the extraction record's `Statistic.family`, and neurostore's `PointValue.kind`. The ingestion workflow's letters map one to one: T, Z, F, D, G, R, B, P.
Which side of a sign split a point is on follows from its values:
- A negative value is always on the inverse side, whatever its kind. A negative p, F
  or chi-square means the column is signed or mislabelled.
- Only p, F and chi-square are non-directional. Every other kind is directional,
  `other` included.
- A missing or unknown kind splits by the value's sign, like a directional kind. - A point whose values are all p, F or chi-square, or that has none, is unsigned.
The parse stores no sign of its own; readers derive it from `values` with `study_schema.statistics`.
    """
    t = "t"
    """
    Student's t. Ingestion letter T.
    """
    z = "z"
    """
    A z score. Ingestion letter Z.
    """
    f = "f"
    """
    An F statistic. Ingestion letter F. Not directional.
    """
    chi_square = "chi_square"
    """
    Not directional.
    """
    d = "d"
    """
    Cohen's d. Ingestion letter D.
    """
    g = "g"
    """
    Hedges' g. Ingestion letter G.
    """
    r = "r"
    """
    A correlation coefficient. Ingestion letter R.
    """
    beta = "beta"
    """
    A regression coefficient or parameter estimate. Ingestion letter B.
    """
    p = "p"
    """
    A p value. Ingestion letter P. A significance level, not a statistic: never directional, and never the basis of a sign split.
    """
    other = "other"
    """
    A kind the paper names and this list does not; `kind_as_printed` keeps the wording. Directional: it splits by the value's sign.
    """


class SplitHalf(str, Enum):
    """
    Which half of a sign split an analysis is.
    """
    original = "original"
    """
    The analysis as named.
    """
    inverse = "inverse"
    """
    The reversed contrast of the original. A consumer records it as the original's conditions with their weights negated.
    """


class SplitRule(str, Enum):
    """
    The deterministic rule that split an analysis.
    """
    sign_of_directional_statistic = "sign_of_directional_statistic"
    """
    Points with a negative value form the inverse half; every other point, unsigned ones included, forms the original half. An unsigned point's side is the half it was placed in.
    """


class AuditVerdict(str, Enum):
    """
    pondie's verdict on one analysis of the parse it revises.
    """
    accept = "accept"
    """
    The analysis stands as proposed. Its key is unchanged.
    """
    relabel = "relabel"
    """
    The same points, in a different role: an analysis proposed as a result that is a region of interest, a seed, a stimulation target. Its key is unchanged.
    """
    split = "split"
    """
    The points belong to more than one analysis. The replacements have new keys.
    """
    merge = "merge"
    """
    The points belong with another analysis's. The merged analysis has a new key, and every analysis merged into it carries this verdict.
    """
    omit = "omit"
    """
    Not an analysis at all: a demographics table, a duplicate, coordinates quoted from another study. No replacement.
    """
    add = "add"
    """
    An analysis the revised parse did not have, found while extracting the record: a null result stated in the text, a result shown only in a figure, a contrast reported without coordinates. `key` names the new analysis; it revises nothing.
    """


class ClusterMeasure(str, Enum):
    """
    The unit of a reported cluster size.
    """
    voxels = "voxels"
    mm3 = "mm3"
    cm3 = "cm3"
    other = "other"


class TableReadingKind(str, Enum):
    """
    What reading a table for coordinates found.
    """
    coordinates = "coordinates"
    """
    Analyses with points were read from it.
    """
    contrasts_without_coordinates = "contrasts_without_coordinates"
    """
    It lists tested contrasts but reports no coordinates for them -- rows reading "n.s." or "none". Its analyses are in `analyses` with cells and no points.
    """
    no_coordinates = "no_coordinates"
    """
    It holds no coordinates and lists no contrasts: demographics, behaviour, acquisition parameters. No analysis was read from it.
    """
    rejected_by_triage = "rejected_by_triage"
    """
    Triage judged it not worth reading, so it was not read.
    """
    excluded_by_hand = "excluded_by_hand"
    """
    A person marked it as not a coordinate table, so it was not read.
    """


class CorrectionKind(str, Enum):
    """
    A notice attached to a paper by its publisher or indexer.
    """
    erratum = "erratum"
    retraction = "retraction"
    expression_of_concern = "expression_of_concern"
    comment = "comment"
    update = "update"


class ThresholdLevel(str, Enum):
    """
    The level a threshold applies at.
    """
    height = "height"
    """
    Voxel- or vertex-wise, the cluster-forming threshold.
    """
    cluster_extent = "cluster_extent"
    """
    A minimum cluster size.
    """
    cluster_level = "cluster_level"
    """
    A cluster-wise corrected p.
    """
    peak_level = "peak_level"
    """
    A peak-wise corrected p, applied after a height threshold.
    """
    tfce = "tfce"
    """
    Threshold-free cluster enhancement.
    """


class ThresholdQuantity(str, Enum):
    """
    What a threshold's value is.
    """
    p = "p"
    t = "t"
    z = "z"
    f = "f"
    voxels = "voxels"
    mm3 = "mm3"


class ValueLevel(str, Enum):
    """
    What a value at a point describes.
    """
    peak = "peak"
    cluster = "cluster"


class CorrectionMethod(str, Enum):
    """
    How a p value or threshold was corrected for multiple comparisons.
    """
    uncorrected = "uncorrected"
    fwe = "fwe"
    """
    Family-wise error, by random field theory unless stated otherwise.
    """
    fdr = "fdr"
    bonferroni = "bonferroni"
    monte_carlo = "monte_carlo"
    """
    Simulated cluster-size correction, such as 3dClustSim or AlphaSim.
    """
    permutation = "permutation"
    small_volume = "small_volume"
    """
    A correction within a region, such as SPM's small-volume correction.
    """


class ReferenceProvider(str, Enum):
    """
    Where a reference-list entry came from.
    """
    europepmc = "europepmc"
    """
    The Europe PMC references endpoint.
    """
    crossref = "crossref"
    semantic_scholar = "semantic_scholar"
    pubmed = "pubmed"
    source_xml = "source_xml"
    """
    The downloaded full text's own reference list, such as JATS `ref-list`.
    """
    parsed_text = "parsed_text"
    """
    Parsed from plain text, the least reliable.
    """


class CitationAlignment(str, Enum):
    """
    How an in-text citation was tied to its reference entries.
    """
    xref = "xref"
    """
    Exact: the source marks the citation with the entry's id, as JATS `xref ref-type="bibr"` and Elsevier cross-references do.
    """
    numbered = "numbered"
    """
    A bracketed or superscript number read as a list position.
    """
    author_year = "author_year"
    """
    An author-year marker matched to an entry by first author's surname and year, with a letter suffix ("2001a") breaking ties.
    """
    unaligned = "unaligned"
    """
    A citation marker found but tied to no entry.
    """


class AnalysisType(str, Enum):
    """
    The method that produced the statistical map, independent of what was tested about it. A between-group comparison of connectivity, decoding accuracy, or component loadings keeps the method here and records the comparison in Effect. Bound only by ConjunctionComponent.analysis_type; an Analysis states its method by which AnalysisDetails subclass it fills. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    mass_univariate = "mass_univariate"
    """
    Voxelwise, vertexwise, or ROI-wise GLM, mixed-effects model, ANOVA or ANCOVA, or robust regression. This is the default family and takes no details payload.
    """
    multivariate_decoding = "multivariate_decoding"
    """
    Classification or pattern discriminability.
    """
    representational_similarity = "representational_similarity"
    """
    Association at the level of representational dissimilarity matrices. A trial-wise similarity or model-fit regressor entered into a univariate GLM is mass_univariate with a parametric_modulation effect, not this.
    """
    connectivity = "connectivity"
    """
    PPI, gPPI, seed-based connectivity, DCM, covariance, or Granger causality. PPI stays here even when the software estimates it with a GLM.
    """
    conjunction = "conjunction"
    """
    Logical combination of independently defined effects.
    """
    latent_decomposition = "latent_decomposition"
    """
    One component or latent variable of a decomposition -- ICA, PCA, NMF, PLS, CCA, or a multimodal fusion. How many blocks were decomposed is not a method family: it is `LatentDecompositionDetails.second_block`. A conjunction component needing the distinction states it in this field's free-text escape hatch.
    """
    not_structurable = "not_structurable"
    """
    The effect is grounded in the source but has no stable structured decomposition.
    """


class SpatialScope(str, Enum):
    """
    Spatial domain of the analysis, and a meta-analysis inclusion criterion. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    whole_brain = "whole_brain"
    """
    Inference across the whole acquired volume or surface.
    """
    roi = "roi"
    """
    Inference restricted to one or more regions of interest.
    """
    searchlight = "searchlight"
    """
    Moving-window multivariate analysis across the whole search space.
    """


class AnalysisOutcome(str, Enum):
    """
    Whether the tested effect produced any finding at the threshold the source applied. Closed: the two are the only answers, and a source that does not say takes `not_reported` rather than a third value.
    """
    significant_effect = "significant_effect"
    """
    At least one cluster, peak, region or test survived the source's own threshold.
    """
    no_significant_effect = "no_significant_effect"
    """
    The effect was tested and nothing survived the source's own threshold -- "no significant differences were found", a table row reading "none", a null correlation.
    """


class SpatialUnit(str, Enum):
    """
    The element an analysis was carried out over: the surface-versus-volume distinction as well as the univariate-versus-parcellated one. Gives the element, where SpatialScope gives the extent. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    voxel = "voxel"
    """
    Volumetric voxels.
    """
    vertex = "vertex"
    """
    Surface vertices, on a reconstructed cortical mesh. Results are vertex indices in a surface template rather than stereotactic coordinates.
    """
    roi = "roi"
    """
    One value per region, from an averaged or extracted regional summary rather than an element-wise map.
    """
    parcel = "parcel"
    """
    Parcels of a parcellation covering the search space, as distinct from a small set of named regions of interest.
    """


class EffectKind(str, Enum):
    """
    What kind of test an effect's cells describe. The range of `Effect.kind`, and also the output of deriving the same thing from the cells -- the two are compared, and a disagreement is a record contradicting itself.
This once had no slot at all, on the reasoning that the kind follows entirely from the cells and storing it would put one fact in two places. It does put it in two places, and that turned out to be the reason to store it: a cell pattern that derives nothing, or derives something other than what the analysis is, was invisible while the record stated the shape only once. There is no free-text branch: a cell pattern yields one of these labels or none, and a pattern yielding none is a record whose cells do not describe a test. The derivation is stated once, in extraction-readme.md §3.
    """
    simple_effect = "simple_effect"
    """
    A quantity tested against zero rather than against another level. Covers activation and deactivation against the unmodelled implicit baseline, decoding accuracy above chance, dissimilarity above zero, and connectivity different from zero.
    """
    contrast = "contrast"
    """
    One term compared against itself. Whether it reads as a group comparison, a condition comparison, a pre-post change or a region comparison follows from what that term's levels range over, not from a different field.
    """
    interaction = "interaction"
    """
    Two comparisons at once -- a group factor and a condition factor together, occasions and arms, or either of those and a factor whose levels are not entities at all, such as region, hemisphere, task or frequency band. Also the kind of a **moderation**, a crossing one of whose terms is continuous.
    """
    parametric_modulation = "parametric_modulation"
    """
    A tested continuous term varying within subject.
    """
    cross_subject_regression = "cross_subject_regression"
    """
    A tested continuous term varying between subject or mixed.
    """
    omnibus = "omnibus"
    """
    A multi-degree-of-freedom test with no direction to give -- an F or a chi-square over a factor's levels or over an interaction's degrees of freedom. A comparison whose direction the source merely withheld is not this.
    """


class EffectPath(str, Enum):
    """
    The path through a mediation model represented by an effect's map. Without it, an indirect-effect map is structurally identical to a plain regression on the same predictor, and a synthesis would pool the two.
No `not_applicable` value is needed: an effect outside a mediated path has no `Mediation` object or slot to fill.
    """
    direct = "direct"
    """
    The effect of the primary term with the mediator controlled.
    """
    indirect = "indirect"
    """
    The mediated path, for example a product of coefficients.
    """
    total = "total"
    """
    The unmediated total effect.
    """


class ModelFamily(str, Enum):
    """
    Statistical model family used to estimate the effect. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    glm = "glm"
    """
    An ordinary least-squares general linear model, including the summary-statistics two-stage approach that fMRI calls a random-effects analysis: the group stage is still a GLM on contrast images.
    """
    mixed_effects = "mixed_effects"
    """
    A model estimating random effects directly, rather than by summarizing a first stage -- a linear mixed model, a hierarchical model.
    """
    anova = "anova"
    """
    Analysis of variance, with no continuous covariate.
    """
    ancova = "ancova"
    """
    Analysis of covariance: a factorial design with a continuous covariate controlled for.
    """
    robust_regression = "robust_regression"
    """
    A regression fitted to resist outliers, such as an iteratively reweighted or M-estimator fit.
    """


class StatisticFamily(str, Enum):
    """
    Test statistic family for the tested effect, independent of the thresholding procedure recorded in InferenceSettings. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    t = "t"
    """
    Student's t. A single-degree-of-freedom statistic, so only the denominator degrees of freedom are populated.
    """
    z = "z"
    """
    Has no degrees of freedom, so both numerator and denominator stay unset.
    """
    f = "f"
    """
    Normally the only family besides likelihood_ratio to populate the numerator.
    """
    chi_square = "chi_square"
    """
    A chi-square statistic.
    """
    likelihood_ratio = "likelihood_ratio"
    """
    A likelihood-ratio statistic, from comparing a model against a nested one.
    """
    beta = "beta"
    """
    A regression coefficient reported as the test statistic itself, which some papers do instead of giving a t or z.
    """
    correlation = "correlation"
    """
    A correlation coefficient reported as the statistic, r or rho.
    """


class MeasureFamily(str, Enum):
    """
    Broad imaging or signal family, for coarse filtering. A BOLD-derived connectivity or decoding result stays functional_bold: derived measures take the family of the underlying signal. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    functional_bold = "functional_bold"
    """
    The BOLD signal and anything derived from it, including connectivity, decoding performance, and amplitude measures.
    """
    structural_morphometry = "structural_morphometry"
    """
    Measures of tissue shape and quantity from a structural image -- volume, thickness, surface area, density.
    """
    diffusion = "diffusion"
    """
    Measures from diffusion-weighted imaging.
    """
    perfusion = "perfusion"
    """
    Blood flow and volume measures, from ASL or a contrast agent.
    """
    molecular_imaging = "molecular_imaging"
    """
    PET and SPECT measures of a tracer's distribution or binding.
    """
    electrophysiology = "electrophysiology"
    """
    EEG, MEG, and intracranial electrical measures.
    """


class MeasureType(str, Enum):
    """
    Normalized scientific quantity of the map, for cross-study queries. Activation and deactivation are directions rather than measure types; both are bold_response and the directional roles carry the direction. Gray-matter density is not collapsed into volume. A paper that does not identify the measure leaves the slot `extraction_status: not_reported`. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    bold_response = "bold_response"
    """
    BOLD activation, task activation, or task-evoked response.
    """
    bold_derived_metric = "bold_derived_metric"
    """
    ALFF, fALFF, regional homogeneity, and similar derived BOLD metrics.
    """
    gray_matter_volume = "gray_matter_volume"
    """
    The quantity of grey matter, from voxel-based or region-based morphometry.
    """
    gray_matter_density = "gray_matter_density"
    """
    Gray-matter density or concentration, kept distinct from volume.
    """
    white_matter_volume = "white_matter_volume"
    """
    The quantity of white matter.
    """
    cortical_thickness = "cortical_thickness"
    """
    The distance between the grey-white boundary and the pial surface.
    """
    surface_area = "surface_area"
    """
    The area of a cortical surface or one of its parcels.
    """
    structural_morphometry_other = "structural_morphometry_other"
    """
    A structural measure none of the named ones covers -- gyrification, sulcal depth, a shape descriptor.
    """
    diffusion_metric = "diffusion_metric"
    """
    Fractional anisotropy, mean diffusivity, and similar; name the metric in specific_metric.
    """
    cerebral_blood_flow = "cerebral_blood_flow"
    """
    Perfusion as a flow rate, from ASL or a tracer.
    """
    cerebral_blood_volume = "cerebral_blood_volume"
    """
    The fraction of tissue occupied by blood, distinct from the rate at which it flows.
    """
    metabolic_rate = "metabolic_rate"
    """
    A rate of consumption or turnover, such as the glucose metabolic rate from FDG- PET.
    """
    receptor_binding = "receptor_binding"
    """
    PET receptor-binding potential.
    """
    tracer_uptake = "tracer_uptake"
    """
    How much tracer accumulated, as an uptake value rather than a modelled rate or binding parameter.
    """
    electrophysiological_amplitude = "electrophysiological_amplitude"
    """
    The size of a voltage or field deflection in the time domain, such as an evoked- potential peak.
    """
    electrophysiological_power = "electrophysiological_power"
    """
    Signal power in a frequency band. The band itself is not a field here; name it in specific_metric.
    """
    connectivity_strength = "connectivity_strength"
    """
    PPI, seed correlation, or DCM parameter.
    """
    decoding_performance = "decoding_performance"
    """
    Classifier accuracy or other pattern-discriminability performance.
    """
    representational_similarity = "representational_similarity"
    """
    Model-brain similarity from an RDM-level association.
    """
    component_loading = "component_loading"
    """
    ICA or PCA spatial loading.
    """


class Prespecification(str, Enum):
    """
    Whether a contrast was planned before the data were seen. A preregistered primary contrast and a post-hoc sweep from the same paper are not equivalent evidence, and a synthesis that cannot tell them apart cannot address selective reporting.
    """
    preregistered = "preregistered"
    """
    The analysis was fixed in advance in a record outside the paper: a registry entry, a trial identifier, a registered report, a published protocol or analysis plan. The claim must be the source's, and a registration covering the study does not by itself cover every contrast reported from it.
    """
    planned = "planned"
    """
    The paper itself says the analysis was planned before the data were seen -- a planned contrast, an a priori hypothesis it tests, a confirmatory or hypothesis-driven analysis -- with no registration or protocol behind the claim. Fixed in advance by the authors' account, which a reader cannot check the way a registration can.
    """
    exploratory = "exploratory"
    """
    The source presents the analysis as exploratory, post hoc, data-driven, or follow-up to something else it found. A positive statement by the authors, not an inference from an absent registration.
    """


class TermType(str, Enum):
    """
    Whether a model term is categorical or continuous.
    """
    categorical = "categorical"
    """
    A factor, defined by its levels and the cohorts, conditions, occasions, or arms carrying them. Its cells name a `level`, and a cell's `direction` is the sign of the contrast weight put on that level -- something the analyst specified.
    """
    continuous = "continuous"
    """
    Carries the slope facts, and has no levels. Its cell names no `level`, there being no level for a slope to be, and the cell's `direction` is the sign of the fitted coefficient -- something the data produced rather than something specified.
    """


class VariationLevel(str, Enum):
    """
    The level at which a term varies -- whether it moves within a participant or only across the sample. A property of **any** term, categorical or continuous: a repeated-measures factor and a trial-wise modulator are both within-subject, and a diagnosis factor and an age covariate are both between-subject.
For a continuous term it is what separates a parametric modulation from a cross-subject regression, and the derived kind of an effect testing it reads this. For a categorical factor it feeds no derivation; it is the factor's scope, and two studies that crossed a factor within participants and between them did not estimate the same thing. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    within_subject = "within_subject"
    """
    The term moves within a participant: a continuous term taking many values trial to trial or scan to scan, which is the level a parametric modulation is estimated at, or a categorical factor every participant met every level of -- a repeated-measures or crossover design.
    """
    between_subject = "between_subject"
    """
    The term varies only across the sample: one value per participant for a continuous term, or a categorical factor each participant sits in exactly one level of, as a diagnosis or a parallel-group allocation does.
    """
    mixed = "mixed"
    """
    The term varies both within and between participants: age in a longitudinal study, where each person ages and people also differ in age at entry, or a partially crossed factor some participants met every level of and others did not.
    """


class Direction(str, Enum):
    """
    How a term entered or came out of an analysis, using one vocabulary for every term type. Both a categorical level on the plus side of a comparison and a continuous term with a positive coefficient are `positive`. The referenced term's `type` distinguishes them. For a cell over a **product** term, this field gives the interaction coefficient's sign, not either component's slope.
It is a sign, not a magnitude: numeric contrast weights are never recorded, and a contrast whose magnitudes matter keeps them in `Analysis.definition`. There is no value for a zero weight either -- a level the contrast did not weight has no `Cell` at all.
Only `positive` and `negative` are directional. A cell can record no sign three ways -- `undirected`, `held`, or `extraction_status: not_reported` -- and choosing between them is the decision rule in extraction-readme.md §2.
    """
    positive = "positive"
    """
    A level on the plus side of the comparison, or a coefficient under which the measure rises as the term rises.
    """
    negative = "negative"
    """
    A level on the minus side of the comparison, or a coefficient under which the measure falls as the term rises.
    """
    undirected = "undirected"
    """
    The test yields no per-level sign, so there is none to report. An F or chi-square over a factor compares that factor's levels against each other and returns one statistic for the set: every one of its levels takes a cell with this value, and a multi-degree-of-freedom interaction F takes it on the cell over the product column.
    Not `extraction_status: not_reported`: the sign is not missing from the page, it is absent from the test, so there is something to record rather than nothing. The post-hoc contrast that would supply one is a different Analysis.
    """
    held = "held"
    """
    A level the contrast was taken *within*, which appears on **both sides** of the comparison and so has no net sign -- "patients versus controls, in the task condition" has task on the plus side and the minus side at once. Cell that one level and leave its factor's other levels **absent**, where an undirected test cells every level.
    No report, however complete, could sign this cell, which is what separates it from both unsigned neighbours: `undirected` is a test that produces no sign, a sign the page withheld is `extraction_status: not_reported`, and this is a sign that is not defined. A cell that names no level -- on a slope or a product column -- can never sit on both sides, so it can never take this value.
    """


class FunctionalForm(str, Enum):
    """
    Shape of a term's relationship to the measure. A squared term with a negative coefficient is an inverted-U relationship, not a negative association, so non-linear and transformed terms must not be reported as linear. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    linear = "linear"
    """
    The measure changes by a constant amount per unit of the term.
    """
    quadratic = "quadratic"
    """
    A squared term. With a negative coefficient this is an inverted-U, not a negative association.
    """
    absolute = "absolute"
    """
    Unsigned-magnitude regressors such as an absolute prediction error or an unsigned log-evidence.
    """
    log = "log"
    """
    The term was log-transformed before entering the model.
    """


class ConnectivityMethod(str, Enum):
    """
    Method used to estimate connectivity. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    ppi = "ppi"
    """
    Psychophysiological interaction: connectivity with a seed that changes with a psychological condition.
    """
    gppi = "gppi"
    """
    Generalized PPI, which models every condition rather than a single contrast.
    """
    seed_based = "seed_based"
    """
    Correlation between a seed's time series and every other element, with no interaction term.
    """
    dcm = "dcm"
    """
    Dynamic causal modelling, which estimates directed influence from a generative model.
    """
    granger = "granger"
    """
    Granger causality, which infers direction from temporal precedence.
    """
    coherence = "coherence"
    """
    Frequency-domain coupling between two signals.
    """
    structural_covariance = "structural_covariance"
    """
    Correlation of a structural measure between regions across participants, rather than of a signal within one. The seed and target are regions as in any other method here, but the correlation runs over subjects, so there is no time series.
    """
    multivariate = "multivariate"
    """
    Pattern-based connectivity: multivoxel or informational connectivity between ensembles of voxels rather than between averaged time series.
    """


class InferenceTarget(str, Enum):
    """
    What the connectivity analysis drew inference about. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    connectivity_parameter = "connectivity_parameter"
    """
    The test was on the strength of a connection.
    """
    model_comparison = "model_comparison"
    """
    The test was on which of several models fits better, not on any one parameter.
    """
    network = "network"
    """
    The test was on a set of connections treated as a unit, rather than on individual edges.
    """


class EdgeDirectionality(str, Enum):
    """
    Whether a connectivity edge is genuinely directed. Only directed models such as DCM and Granger causality qualify; a seed-to-voxel PPI or correlation is undirected, and its sign travels with the edge rather than implying a direction.
The one vocabulary nothing reads off the page: `ConnectivityEdge.directionality` is derived from `ConnectivityDetails.connectivity_method`, since the method decides it and no wording can override it.
    """
    directed = "directed"
    """
    The method supports a claim about which region influences which.
    """
    undirected = "undirected"
    """
    The method gives a symmetric relationship only, whatever the wording of the paper.
    """


class PerformanceRelation(str, Enum):
    """
    Direction of a decoding performance metric relative to its reference value.
    """
    above_reference = "above_reference"
    """
    Performance exceeded its reference value.
    """
    below_reference = "below_reference"
    """
    Performance fell below its reference value.
    """
    not_applicable = "not_applicable"
    """
    The measure has no reference to compare against.
    """


class NullHypothesis(str, Enum):
    """
    The null hypothesis tested by a conjunction. Only the conjunction null supports the interpretation that every component effect is present, so the hypothesis is recorded separately from the procedure that implemented it.
    """
    global_null = "global_null"
    """
    At least one component effect is present at a voxel.
    """
    conjunction_null = "conjunction_null"
    """
    Every component effect is present at a voxel.
    """


class ConjunctionImplementation(str, Enum):
    """
    Procedure used to compute the conjunction, which is not the same statement as the null hypothesis it tested: a minimum-statistic test is the usual implementation of the conjunction null. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    minimum_statistic = "minimum_statistic"
    """
    Each element takes the smaller of its statistics, so a conjunction survives only where both effects do.
    """
    masking = "masking"
    """
    One effect's map was thresholded and used to mask the other.
    """
    logical_or = "logical_or"
    """
    Elements surviving either effect were combined, which tests the global null rather than the conjunction null.
    """


class SecondBlock(str, Enum):
    """
    What a decomposition crossed the brain block with, one value per block. This decides whether two decompositions answer the same question, so it is the payload's one required vocabulary -- a task PLS and a behavioural PLS are not poolable, and neither is a one-block ICA with either of them.
Multivalued, and `none` is a value rather than an absent field: a one-block decomposition is a positive assertion, not a gap. Name the blocks and not their number -- a design-plus-behaviour PLS is `[design, behavioral]`, and the count follows from the list's length.
Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    none = "none"
    """
    The brain data were decomposed alone -- ordinary ICA, PCA, or a related single-block method. The commonest case by a wide margin.
    """
    design = "design"
    """
    The experimental design, as in mean-centred task PLS, including the spatiotemporal variant that carries a time dimension.
    """
    behavioral = "behavioral"
    """
    Participant-level behavioural or clinical measures. Where those measures are `Assessment` records of this study, `second_block_assessments` names them.
    """
    seed_activity = "seed_activity"
    """
    Activity in one or more seed regions, named in `second_block_detail`. A connectivity question asked with decomposition machinery.
    """
    other_imaging_modality = "other_imaging_modality"
    """
    A second (or third) imaging measure of the same participants -- the multimodal fusion case. Joint, linked and parallel ICA and mCCA+jICA all land here, and a three-modality fusion carries this value once per additional modality.
    """
    genetic = "genetic"
    """
    Genotype data such as a SNP array. Not an `Assessment`, so its contents belong in `second_block_detail`.
    """


class DecompositionMethod(str, Enum):
    """
    The algorithm that produced the components or latent variables, which decides what their values and signs mean. Independent of `second_block`, since one block structure is reachable by several algorithms: a brain-behaviour covariance can be decomposed by PLS or by CCA. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    ica = "ica"
    """
    Independent component analysis.
    """
    tensor_ica = "tensor_ica"
    """
    ICA over a subject-by-time-by-space tensor, giving one shared spatial map with per-subject loadings.
    """
    joint_ica = "joint_ica"
    """
    ICA on features concatenated across modalities, sharing one mixing matrix. Takes `other_imaging_modality` in `second_block`.
    """
    parallel_ica = "parallel_ica"
    """
    ICA run on two blocks at once with their mixing profiles linked, so a component of one block is paired with a component of the other. Covers linked ICA.
    """
    pca = "pca"
    """
    Principal component analysis, whose components are orthogonal rather than independent.
    """
    nmf = "nmf"
    """
    Non-negative matrix factorization, whose components cannot take negative values.
    """
    dictionary_learning = "dictionary_learning"
    """
    A sparse decomposition learning an overcomplete set of components.
    """
    pls = "pls"
    """
    Partial least squares, where the source does not distinguish the correlation and regression variants.
    """
    pls_correlation = "pls_correlation"
    """
    PLS correlation (PLS-C), decomposing the cross-block correlation matrix by SVD. The variant most fMRI work means by "PLS".
    """
    pls_regression = "pls_regression"
    """
    PLS regression, which predicts one block from the other rather than decomposing their shared covariance symmetrically.
    """
    cca = "cca"
    """
    Canonical correlation analysis, which maximizes correlation between blocks where PLS maximizes covariance.
    """
    mcca = "mcca"
    """
    Multi-set CCA, over three or more blocks. Frequently chained into joint ICA as mCCA+jICA, which takes this value with `joint_ica` noted in `Analysis.model_representation_notes` when the chaining matters.
    """


class MapQuantity(str, Enum):
    """
    What the values of a component or latent-variable map represent. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    loading = "loading"
    """
    How strongly each participant or time point expresses the component.
    """
    weight = "weight"
    """
    The component's contribution at each element, in the decomposition's own scale.
    """
    salience = "salience"
    """
    A PLS salience: the element's contribution to a latent variable. Distinct from `weight`, saliences being conventionally reported as bootstrap ratios -- stability measures, not test statistics, so the threshold applied to them is `salience_threshold` and not a voxelwise statistic threshold.
    """
    z_score = "z_score"
    """
    The component map after standardizing its values.
    """
    spatial_map = "spatial_map"
    """
    The component's spatial pattern, where the source does not say what the values are.
    """


class PolaritySemantics(str, Enum):
    """
    Whether the sign of a component map carries meaning. Decomposition methods can return components whose polarity is arbitrary, in which case a negative loading is not a decrease.
    """
    meaningful = "meaningful"
    """
    The sign is interpretable: a negative value means a decrease.
    """
    arbitrary = "arbitrary"
    """
    The method could have returned the component with its sign flipped, so a negative value does not mean a decrease.
    """
    unsigned = "unsigned"
    """
    The values carry no sign at all.
    """


class NotStructurableReason(str, Enum):
    """
    Why a grounded effect has no stable structured decomposition. Open vocabulary: write the source's own wording in the field when nothing here fits.
    """
    method_specific_derived_metric = "method_specific_derived_metric"
    """
    The tested quantity is a metric peculiar to one method, with no counterpart in the shared vocabulary.
    """
    insufficient_standard_structure = "insufficient_standard_structure"
    """
    The design has too little of the usual structure -- no conditions, no groups, no terms -- to decompose.
    """
    source_too_vague = "source_too_vague"
    """
    The paper reports an effect without saying enough about it to structure.
    """


class TablePurpose(str, Enum):
    """
    What a table is for. A coordinate table is not an analysis merely by having coordinates in it: a study's ROI definitions, its atlas parcels, its connectivity seeds and the peaks of its independent components are all locations rather than findings, and `reported_effect` is what says the rows ARE a finding. Open vocabulary: write the source's own wording when nothing here fits.
    """
    reported_effect = "reported_effect"
    """
    The rows ARE the foci of a tested effect, so this table is an analysis and not one of the kinds below. Derived rather than read: a table an `Analysis` names in `tables` reports that analysis's result.
    Present because absence could not say it: an unmarked table is both one that reports results and one nobody decided about, and a reader shown only the non-analysis kinds has no way to say "it is an analysis".
    """
    region_definitions = "region_definitions"
    """
    Regions of interest the study delimited, with the coordinates that locate them -- a sphere's centre, a mask's peak.
    """
    atlas_or_parcellation = "atlas_or_parcellation"
    """
    Entries of a published atlas or parcellation the study used.
    """
    connectivity_seeds = "connectivity_seeds"
    """
    The seed or node locations a connectivity analysis was run from.
    """
    component_peaks = "component_peaks"
    """
    Peak locations of the components of a latent decomposition -- an ICA component's spatial map. The decomposition is not itself a tested effect.
    """
    prior_literature_coordinates = "prior_literature_coordinates"
    """
    Coordinates cited from other papers, for comparison or to place an ROI.
    """
    stimulus_or_task_list = "stimulus_or_task_list"
    """
    The stimuli, conditions or trial structure of the paradigm.
    """
    demographics = "demographics"
    """
    Participant characteristics, whether or not group differences in them were tested.
    """
    descriptive_statistics = "descriptive_statistics"
    """
    Summary values with no inferential test -- means, percentages, dwell times.
    """


class CoordinateRole(str, Enum):
    """
    What a set of reported coordinates is for. A paper prints coordinates for six reasons, and only the first is a finding; the rest locate something the study used, measured with, quoted, or showed. Open vocabulary: write the source's own wording when nothing here fits.
    """
    result = "result"
    """
    A finding of this study: the peaks, clusters, local maxima or centres of gravity of a tested effect. `result_kind` says what kind of analysis produced it.
    """
    anchor = "anchor"
    """
    A location that defines an analysis rather than resulting from one: a region of interest, a connectivity seed, a stimulation target, a network node. `anchor_kind` says which.
    """
    localization = "localization"
    """
    Where a sensor, electrode, fiducial, intracranial contact, dipole or anatomical landmark is. Metadata about a measurement, not a finding.
    """
    reference = "reference"
    """
    Coordinates quoted from other studies for comparison. A cited location used to place a region of interest is an `anchor`, not a reference.
    """
    display = "display"
    """
    A location used only to show a figure: a slice position, crosshairs, an example voxel. Found in text, almost never in tables.
    """
    other = "other"
    """
    A real brain coordinate in the paper that is not a result, anchor, localization, reference or display: a simulated source position or lesion centre, a worked-example voxel of an atlas. Numbers that are not brain coordinates (lattice points, phantom or rodent bregma positions, orientation vectors) are not coordinates at all and are left out of the parse, not given this role.
    """


class ResultKind(str, Enum):
    """
    The kind of analysis a `result` came from, coarse enough to read from a table or a sentence. An analysis the record models in full states its method in `details` and its test in `Effect.kind`; this is the label for a coordinate set either way. Open vocabulary.
    """
    contrast = "contrast"
    """
    Conditions, groups or tasks compared (A > B, patients > controls).
    """
    association = "association"
    """
    Signal varying with a continuous variable: a correlation, a parametric modulation, a regression on symptoms, age or performance.
    """
    multivariate = "multivariate"
    """
    Decoding, searchlight, classifier weights, representational similarity.
    """
    morphometric = "morphometric"
    """
    A structural effect -- volume, thickness, density, shape.
    """
    lesion = "lesion"
    """
    Lesion locations, or lesion-symptom and lesion-network mapping.
    """
    connectivity = "connectivity"
    """
    Regions whose connectivity with a seed is the finding. The seed itself is an `anchor`.
    """


class AnchorKind(str, Enum):
    """
    What an `anchor` coordinate set defines. Open vocabulary.
    """
    roi = "roi"
    """
    A region of interest or sphere that data were extracted from or restricted to.
    """
    seed = "seed"
    """
    The seed of a connectivity, PPI or DCM analysis.
    """
    stimulation_target = "stimulation_target"
    """
    Where TMS, tDCS, DBS or focused ultrasound was delivered.
    """
    node = "node"
    """
    An atlas parcel or network node definition.
    """



class ArtifactHeader(ConfiguredBaseModel):
    """
    Who made an artifact, from what, for which paper.
    """
    artifact_kind: ArtifactKind = Field(default=...)
    schema_version: str = Field(default=..., description="""The version of this schema the artifact validates against.""")
    article_id: str = Field(default=..., description="""The ingestion catalog's key for the paper. Minted once, at download, and never recomputed from the identifiers below.""")
    identifiers: ArticleIdentifiers = Field(default=...)
    producer: Producer = Field(default=...)
    inputs: Optional[list[InputRef]] = Field(default=None, description="""Every artifact this one was made from, by fingerprint.""")
    created_at: Optional[datetime ] = Field(default=None)


class ArticleIdentifiers(ConfiguredBaseModel):
    """
    Every identifier known for the paper when the artifact was written. Carried whole, so no consumer has to choose between them or look one up.
    """
    pmid: Optional[str] = Field(default=None)
    pmcid: Optional[str] = Field(default=None)
    doi: Optional[str] = Field(default=None)
    neurostore_base_study_id: Optional[str] = Field(default=None, description="""Set once the paper has been uploaded; neurostore's BaseStudy id.""")


class Producer(ConfiguredBaseModel):
    """
    The program and stage that wrote an artifact.
    """
    name: str = Field(default=..., description="""ns-pond-ingestion-workflow or pondie.""")
    version: str = Field(default=...)
    stage: Optional[str] = Field(default=None, description="""The stage within the producer, such as extract, space or audit.""")
    model: Optional[str] = Field(default=None, description="""The language model a stage called, if any.""")
    prompt_version: Optional[str] = Field(default=None)


class InputRef(ConfiguredBaseModel):
    """
    One artifact another was made from.
    """
    artifact_kind: str = Field(default=..., description="""A parse ArtifactKind, or the name of another artifact kind such as an extraction record or a downloaded file.""")
    fingerprint: str = Field(default=..., description="""The input's identity: `text_sha256` for a parsed paper, `parse_id` for a coordinate parse, a sha256 otherwise.""")
    producer_version: Optional[str] = Field(default=None)


class TextSpan(ConfiguredBaseModel):
    """
    A range of the parsed paper's text, by character offset.
    """
    start_char: int = Field(default=..., ge=0)
    end_char: int = Field(default=..., description="""Exclusive.""", ge=0)
    text: Optional[str] = Field(default=None, description="""The characters in the range, kept so a reader can check the offsets.""")


class ParsedPaper(ConfiguredBaseModel):
    """
    One paper as text, tables and bibliographic facts. The same shape for every download source.
    The text is the only offset space. Every evidence span an extraction record cites, every table row's position and every text-read point addresses `text_sha256`'s characters, so a span can be checked by slicing the text, and a span made against a different text is detectably wrong.
    """
    header: ArtifactHeader = Field(default=...)
    source: Union[DocumentSource, str] = Field(default=...)
    source_reason: Optional[str] = Field(default=None, description="""Why this source's text was chosen over the others downloaded, such as \"most tables\" or \"first in download order\". Every stage reads this one text, so the choice is made once and recorded.""")
    text_path: str = Field(default=..., description="""The text file's path, relative to the paper's bundle directory.""")
    text_sha256: str = Field(default=..., description="""sha256 of the text file's UTF-8 bytes. This artifact's fingerprint.""")
    text_length: Optional[int] = Field(default=None, ge=0)
    bibliography: Bibliography = Field(default=...)
    is_meta_analysis: bool = Field(default=..., description="""Whether the paper is itself a meta-analysis or review, decided here once. Every consumer reads this field; none applies its own test.""")
    is_meta_analysis_basis: Optional[MetaAnalysisBasis] = Field(default=None)
    sections: Optional[list[Section]] = Field(default=None)
    supplements: Optional[list[Supplement]] = Field(default=None, description="""Supplementary material the paper links to, and whether it was fetched. A result the text cites to a supplement that was not fetched is reported elsewhere, not missing.""")
    references: Optional[list[Reference]] = Field(default=None, description="""The paper's reference list, in order. Usually fetched from an API by the paper's identifiers rather than parsed from the text (`Reference.provider` says which), so it is complete and carries DOIs even when the text's list is badly extracted.""")
    citations: Optional[list[Citation]] = Field(default=None, description="""Every in-text citation, where it sits in the text and which reference it points to. The link from a sentence to a work, which the reference list alone cannot give: what resolves the citations a task's description makes (storage `Task.reference_ids`) and traces a task to the paper that introduced it.""")
    tables: Optional[list[ParsedTable]] = Field(default=None)


class Bibliography(ConfiguredBaseModel):
    """
    The paper's bibliographic facts, as the metadata lookup returned them. Downstream they are copied, never extracted: pondie fills the record's Study.title, authors, doi, journal, publication_year, language and study_type from here, and neurostore fills BaseStudy from here.
    """
    title: str = Field(default=...)
    authors: Optional[list[str]] = Field(default=None, description="""Author names in published order.""")
    journal: Optional[str] = Field(default=None)
    publication_year: Optional[int] = Field(default=None)
    volume: Optional[str] = Field(default=None)
    issue: Optional[str] = Field(default=None)
    pages: Optional[str] = Field(default=None)
    abstract: Optional[str] = Field(default=None)
    language: Optional[list[str]] = Field(default=None)
    publication_types: Optional[list[str]] = Field(default=None, description="""PubMed publication types, verbatim. The storage schema's Study.study_type.""")
    keywords: Optional[list[str]] = Field(default=None)
    license: Optional[str] = Field(default=None)
    open_access: Optional[bool] = Field(default=None)
    corrections: Optional[list[Correction]] = Field(default=None, description="""Notices attached to the paper -- errata, retractions, expressions of concern -- as the indexer lists them. A retracted paper is still parsed and stored, marked by its `retraction` notice, and left out of studysets by default; a filter can ask for it explicitly.""")
    provider: Optional[str] = Field(default=None, description="""The metadata service the facts came from, such as pubmed or europepmc.""")


class Reference(ConfiguredBaseModel):
    """
    One entry of a paper's reference list.
    """
    id: str = Field(default=..., description="""Stable within the paper: the source's own id where it has one (a JATS `ref` id such as `B12`), else `ref<position>`.""")
    position: Optional[int] = Field(default=None, description="""1-based order in the list, which a numbered citation style cites by.""", ge=1)
    provider: Optional[Union[ReferenceProvider, str]] = Field(default=None, description="""Where the entry came from.""")
    label: Optional[str] = Field(default=None, description="""How the text cites it: the number of a numbered style (\"12\"), or the author-year key of an author-year style (\"Stroop 1935\").""")
    text: str = Field(default=..., description="""The entry as printed.""")
    doi: Optional[str] = Field(default=None)
    pmid: Optional[str] = Field(default=None)
    title: Optional[str] = Field(default=None)
    year: Optional[int] = Field(default=None)


class Citation(ConfiguredBaseModel):
    """
    One in-text citation and the reference entries it names. A grouped citation (\"[3-5]\", \"(Smith, 2001; Jones, 2003)\") is one Citation with several references.
    """
    text_span: TextSpan = Field(default=..., description="""The citation marker in the text.""")
    references: Optional[list[str]] = Field(default=None, description="""The entries it names, by `Reference.id`. Empty when it could not be aligned.""")
    method: CitationAlignment = Field(default=..., description="""How the marker was tied to its entries -- what its reliability rests on.""")
    confidence: Optional[float] = Field(default=None, description="""For a heuristic alignment, how sure; absent for an exact one.""", ge=0, le=1)


class Correction(ConfiguredBaseModel):
    """
    One notice attached to a paper.
    """
    kind: Union[CorrectionKind, str] = Field(default=...)
    pmid: Optional[str] = Field(default=None)
    doi: Optional[str] = Field(default=None)


class Supplement(ConfiguredBaseModel):
    """
    One item of supplementary material.
    """
    label: Optional[str] = Field(default=None)
    url: Optional[str] = Field(default=None)
    fetched: bool = Field(default=...)
    path: Optional[str] = Field(default=None, description="""Where the fetched file is, relative to the bundle directory.""")


class Section(ConfiguredBaseModel):
    """
    A span of the text and what it is.
    """
    kind: Union[SectionKind, str] = Field(default=...)
    heading: Optional[str] = Field(default=None, description="""The heading as printed.""")
    start_char: int = Field(default=..., ge=0)
    end_char: int = Field(default=..., ge=0)


class ParsedTable(ConfiguredBaseModel):
    """
    A table of the paper, cell by cell.
    """
    table_id: str = Field(default=..., description="""The table's key, as the source's parser names it. Stable for the life of the parsed paper and used unchanged by every consumer: the coordinate parse's keys, the record's Table.id, neurostore's Table.t_id. Never renumbered from the printed label and never sanitized differently on disk.""")
    label: Optional[str] = Field(default=None, description="""The printed label, such as Table 2 or Supplementary Table S4.""")
    number: Optional[str] = Field(default=None)
    caption: Optional[str] = Field(default=None)
    footer: Optional[str] = Field(default=None)
    raw_path: Optional[str] = Field(default=None, description="""The source's raw table file, relative to the bundle directory.""")
    column_headings: Optional[list[str]] = Field(default=None)
    rows: Optional[list[TableRow]] = Field(default=None, description="""The body rows, in printed order.""")
    text_span: Optional[TextSpan] = Field(default=None, description="""Where the table's rows are inlined in the text, when the source inlines them.""")
    coordinate_space_hint: Optional[ReportedSpace] = Field(default=None, description="""The source parser's own guess at the table's space. A hint for the coordinate stages, not an answer: the space a point is stored in is the coordinate parse's.""")
    triage: Optional[TableTriage] = Field(default=None)


class TableRow(ConfiguredBaseModel):
    """
    One body row of a table.
    """
    row: int = Field(default=..., description="""The row's index among the table's body rows, from 0. What a coordinate parse's point cites, and so part of every analysis key.""", ge=0)
    cells: Optional[list[str]] = Field(default=None, description="""The row's cells, as printed, in column order.""")
    text_span: Optional[TextSpan] = Field(default=None, description="""Where the row sits in the text, when the table is inlined there.""")


class TableTriage(ConfiguredBaseModel):
    """
    Whether a table is worth reading for coordinates, and why.
    """
    passes: bool = Field(default=...)
    score: Optional[float] = Field(default=None)
    route: Optional[str] = Field(default=None)
    located_by: Optional[str] = Field(default=None)
    excluded_by_hand: Optional[bool] = Field(default=None, description="""A person marked the table as not holding coordinates. Overrides `passes`, and no consumer reads coordinates from it.""")
    exclusion_reason: Optional[str] = Field(default=None)


class CoordinateParse(ConfiguredBaseModel):
    """
    Every coordinate a paper reports, grouped into analyses. An original parse is written by the ingestion workflow; a revision is written by pondie when its audit disagrees with the original.
    A parse is never edited after it is written. A reader that disagrees with it writes a revision instead, and the revision is a complete parse on its own: neurostore can store it as a new version of the paper's analyses without consulting the parse it revises.
    Analyses that pondie accepts or relabels keep their keys, because their cells are unchanged, so claims made against them carry over to the revision untouched. Only a split, a merge or an omission changes which keys exist.
    """
    header: ArtifactHeader = Field(default=..., description="""`inputs` names the parsed paper by `text_sha256`, and for a revision also the parse it revises by `parse_id`.""")
    parse_id: str = Field(default=..., description="""This parse's identity, the fingerprint every later artifact cites. Unique per paper; a sha256 of the canonical JSON of `analyses` is recommended, so two producers that reach the same analyses reach the same id.""")
    text_sha256: str = Field(default=..., description="""The parsed paper's fingerprint. Every point's cells and spans address it.""")
    revision_of: Optional[str] = Field(default=None, description="""The `parse_id` of the parse this one revises. Absent on an original parse, which is how a reader tells the two apart.""")
    analyses: list[ParsedAnalysis] = Field(default=..., description="""May be empty: the parse ran and found no analysis. A paper the parse never ran on has no CoordinateParse at all, so the two are never confused, and `tables` says what reading each table found.""")
    tables: Optional[list[TableReading]] = Field(default=None, description="""One entry per table of the parsed paper: what reading it for coordinates found, or why it was not read. A table with no entry was not considered.""")
    omitted_analyses: Optional[list[OmittedAnalysis]] = Field(default=None, description="""Text or figure analyses the producer read and left out of `analyses`, each with the reason. A table's omissions are in `tables`. Absent when nothing was left out.""")
    text_sweep: Optional[TextSweep] = Field(default=None, description="""How much of the text was searched for coordinates outside tables. Absent when the text was not searched.""")
    verdicts: Optional[list[AnalysisVerdict]] = Field(default=None, description="""On a revision only: one verdict for every analysis of the revised parse, so nothing in it is silently dropped, and an `add` verdict for every analysis the revision introduces that the revised parse lacked. An original parse has none.""")


class ParsedAnalysis(ConfiguredBaseModel):
    """
    The points a paper reports together for one tested effect, or for one non-result purpose such as the regions of interest an analysis used.
    In an original parse, both the grouping and the role are the ingestion workflow's proposal, made from a table and its caption. pondie confirms or overrides them with the whole paper in view.
    """
    key: str = Field(default=..., description="""The analysis's identity, derived from where it was read, so it survives re-runs, reordering and deduplication: a re-run that reads the same place reaches the same key. It is derived from `cells` or `text_spans`, never from `points`, so an analysis with no points -- a contrast a table lists as \"n.s.\" -- still has a key of its own.
For a table analysis, `<table_id>#<h>`. Write `<row>:<column_group>` for each of `cells`, drop duplicates, sort by row and then column group, and join with commas; `h` is the first 12 hex characters of the sha1 of that string's UTF-8 bytes.
For a text or figure analysis, `text#<h>` or `figure#<h>`, built the same way from each of `text_spans` as `<start_char>-<end_char>`, then append `|` and the analysis's `name` normalized (Unicode NFKC, casefolded, en and em dashes as `-`, zero-width characters dropped, whitespace collapsed and stripped). One sentence can name several analyses, so the name is part of the key.
This key is what the extraction record's `Analysis.source_table_analysis` and `CoordinateSet.id` name, and what neurostore stores as `Analysis.source_id`. Two analyses of one parse never cover the same cells, or the same spans under one normalized name, so never share a key.""")
    cells: Optional[list[CellRef]] = Field(default=None, description="""For a table analysis, every cell it was read from: each point's row and column group, and the rows that name the contrast without coordinates. Required for `origin: table`; every point's row and column group is among them.""")
    text_spans: Optional[list[TextSpan]] = Field(default=None, description="""For a text or figure analysis, the sentences or legend it was read from: those holding its coordinates, or the one stating a result that has none.""")
    origin: CoordinateOrigin = Field(default=...)
    table_id: Optional[str] = Field(default=None, description="""The ParsedTable the points were read from. Present exactly when `origin` is `table`.""")
    name: str = Field(default=..., description="""The analysis's label, as printed where the paper prints one.""")
    name_is_printed: Optional[bool] = Field(default=None, description="""False when the producer composed the name because the paper printed none, so a reader never mistakes a placeholder for the paper's wording.""")
    description: Optional[str] = Field(default=None)
    coordinate_space: Optional[ReportedSpace] = Field(default=None, description="""The space of the analysis's points; absent when the paper states none. A point states its own only when it differs.""")
    space_as_printed: Optional[str] = Field(default=None)
    space_basis: Optional[SpaceBasis] = Field(default=None)
    role: Union[CoordinateRole, str] = Field(default=..., description="""What the points are for. Only a `result` is an analysis with a statistic in the extraction record; an `anchor` -- a region of interest, a seed, a stimulation target -- becomes a CoordinateSet there, and never enters a studyset as an analysis.
The ingestion workflow's `roles` stage decides the role. It is a classifier that reads each set and its context; `role_source` names it.
When the classifier is not confident, the proposed role stands. A table set is a `result`. A text set keeps the role the prose stage recorded in these fields (`role`, `anchor_kind`, `from_prior_study`).
Numbers that are not brain coordinates, such as channel numbers or lattice points, get no role. They are not a coordinate set.""")
    anchor_kind: Optional[Union[AnchorKind, str]] = Field(default=None, description="""For an `anchor`, what it defines.""")
    from_prior_study: Optional[bool] = Field(default=None, description="""The coordinates come from another publication rather than from this study: a peak quoted for comparison (always true for `role: reference`), or another study's peak taken as this study's ROI or seed. Separate from the role, because a borrowed seed is still the seed this study's analysis used. False when the study defined them itself, including an ROI built from its own earlier result.""")
    prior_study_evidence: Optional[list[TextSpan]] = Field(default=None, description="""The citation or sentence showing the coordinates come from another publication.""")
    role_confidence: Optional[float] = Field(default=None, description="""The classifier's probability for `role` (and `anchor_kind`). Absent when the proposal stood because no classifier ran.""", ge=0, le=1)
    role_source: Optional[str] = Field(default=None, description="""What decided the role: `proposal` when the proposal stood, otherwise the classifier's name and version, such as `set-role-encoder@2026-10-09`.""")
    split: Optional[SignSplit] = Field(default=None, description="""Present on both halves of an analysis split by sign, and only there. The split is declared here and nowhere else: a reader never infers it from a name.""")
    derived_from: Optional[list[str]] = Field(default=None, description="""On a revision, the keys of the revised parse's analyses this one was made from by a split or a merge. Absent on an analysis carried over unchanged.""")
    statistic: Optional[Union[StatisticKind, str]] = Field(default=None, description="""The test statistic of this analysis's one test -- t, z, F, chi_square -- whatever the columns call it. One analysis is one test. Every value at a point that describes the same test belongs to that point: the statistic, its p value (uncorrected and corrected), an effect size, the cluster's p. A different test is a different analysis, even on the same rows: an omnibus F and the directional post-hoc t that follows it are two analyses, told apart by `column_group` when one table prints both.""")
    statistic_df: Optional[str] = Field(default=None, description="""Degrees of freedom as printed, such as \"1, 38\" or \"27\".""")
    thresholds: Optional[list[Threshold]] = Field(default=None, description="""The thresholds the analysis's results survived, at every level the paper states: most often a voxel-level height (\"p < .001 uncorrected\") together with a cluster-level correction (\"FWE p < .05\"), which one method cannot express. Read from the caption, footer or Methods; each threshold cites where.""")
    points: Optional[list[ParsedPoint]] = Field(default=None, description="""Empty when the paper names the analysis but reports no coordinates for it -- most often because nothing survived the threshold. Whether it found an effect is the extraction record's `Analysis.outcome`; an empty list here only says that no coordinates were printed.""")


class CellRef(ConfiguredBaseModel):
    """
    One table cell an analysis was read from, by row and column group.
    """
    row: int = Field(default=..., description="""The TableRow's `row`.""", ge=0)
    column_group: int = Field(default=..., description="""As on ParsedPoint; 0 in a table with one block of coordinate columns.""", ge=0)


class TableReading(ConfiguredBaseModel):
    """
    What reading one table for coordinates found.
    """
    table_id: str = Field(default=...)
    reading: TableReadingKind = Field(default=...)
    reason: Optional[str] = Field(default=None, description="""For a table not read, why; for an excluded one, who excluded it.""")


class OmittedAnalysis(ConfiguredBaseModel):
    """
    A text or figure analysis the producer read but did not keep, the text counterpart of a `TableReading` with a reason.
    """
    name: str = Field(default=..., description="""The analysis's label as the producer read it.""")
    text_spans: Optional[list[TextSpan]] = Field(default=None, description="""The sentences it was read from, when it was located.""")
    reason: str = Field(default=..., description="""Why it was left out, for example that it repeats a kept analysis (same spans and same normalized name) or that its passage is not in the text.""")


class TextSweep(ConfiguredBaseModel):
    """
    How much of the text was searched for coordinates outside tables, so a reader can tell a complete search that found nothing from one cut short.
    """
    passages_found: Optional[int] = Field(default=None, description="""Passages that looked like they hold coordinates.""", ge=0)
    passages_read: Optional[int] = Field(default=None, description="""Of those, how many were read; fewer when a cap cut the search short.""", ge=0)
    truncated: bool = Field(default=...)
    points_dropped_as_table_restatements: Optional[int] = Field(default=None, description="""Points found in the text but dropped because a table already reports them.""", ge=0)


class SignSplit(ConfiguredBaseModel):
    """
    One half of an analysis the producer split by the sign of its points (see StatisticKind). The original half is the analysis as named, with the points whose values are positive or unsigned; the inverse half is the reversed contrast, with the points whose values are negative. Positive and negative describe statistic values only, never a half: a table of decreases has decreases in its original half.
    pondie extracts the original half and derives the inverse half's record from it by flipping the direction of its cells, so the two never disagree and the inverse half costs no extraction. The derived record carries `mirror_of`, which keeps a meta-analysis from counting one contrast twice.
    The half lives on the analysis, not its points: an unsigned point (only p, F or chi-square values, or none) in a split analysis is on that analysis's side.
    """
    half: SplitHalf = Field(default=...)
    original_analysis: Optional[str] = Field(default=None, description="""On the inverse half, the `key` of the original analysis (the other half of this split) in the same parse. Absent on the original half, and on an inverse half whose original is not in the parse.""")
    rule: SplitRule = Field(default=...)


class ParsedPoint(ConfiguredBaseModel):
    """
    One reported coordinate. `coordinates`, `space` and `values` are NIMADS's point fields with NIMADS's meaning, so the projection to a studyset copies them; everything else is the parse's own.
    """
    coordinates: list[float] = Field(default=..., description="""x, y, z in millimetres.""", min_length=3, max_length=3)
    space: Optional[ReportedSpace] = Field(default=None, description="""Only when it differs from the analysis's `coordinate_space`.""")
    row: Optional[int] = Field(default=None, description="""For a table point, the TableRow it was read from.""", ge=0)
    column_group: Optional[int] = Field(default=None, description="""For a table point, which block of coordinate columns it was read from, numbered from 0 left to right. 0 in a table with one block. Two contrasts printed side by side share rows and differ here.""", ge=0)
    text_span: Optional[TextSpan] = Field(default=None, description="""For a text point, the characters it was read from.""")
    values: Optional[list[PointValue]] = Field(default=None, description="""The values at the point. They are the only record of its sign (StatisticKind gives the rule): a negative value makes it negative, and a point with only p, F or chi-square values, or none, is unsigned and takes the side of its analysis's `split` half. The negative points of a set are their own analysis, the inverse half, declared by `split`; a consumer records the inverse on the contrast's conditions (negated weights), not per point. There is no point-level deactivation flag, and the parse never writes neurostore's Point.deactivation.""")
    cluster_size: Optional[float] = Field(default=None, ge=0)
    cluster_measure: Optional[ClusterMeasure] = Field(default=None)
    is_subpeak: Optional[bool] = Field(default=None)
    label: Optional[str] = Field(default=None, description="""The region name printed beside the point.""")


class PointValue(ConfiguredBaseModel):
    """
    A value reported at a point. NIMADS's point value.
    """
    kind: Union[StatisticKind, str] = Field(default=...)
    kind_as_printed: Optional[str] = Field(default=None)
    value: float = Field(default=...)
    level: Optional[ValueLevel] = Field(default=None, description="""Whether the value describes the peak or the cluster the peak belongs to. A cluster-level p printed on the peak's row is the cluster's.""")
    correction: Optional[Union[CorrectionMethod, str]] = Field(default=None, description="""For a p value, the correction it is under; absent for a statistic or effect size.""")


class Threshold(ConfiguredBaseModel):
    """
    One threshold an analysis's results survived. Maps onto the storage schema's InferenceSettings: a `height` threshold is height_threshold_value and _type, a `cluster_extent` is cluster_extent_threshold, a `cluster_level` is clusterwise_threshold_value, `tfce` sets tfce_used; `correction` is multiple_comparison_method at that level.
    """
    level: ThresholdLevel = Field(default=...)
    quantity: ThresholdQuantity = Field(default=..., description="""What `value` is measured in.""")
    value: Optional[float] = Field(default=None, description="""Absent when the paper names the correction but not the number.""")
    correction: Optional[Union[CorrectionMethod, str]] = Field(default=None)
    scope_as_printed: Optional[str] = Field(default=None, description="""What the correction ran over, as printed, such as \"whole brain\" or \"within the amygdala mask\".""")
    text_span: Optional[TextSpan] = Field(default=None, description="""Where the threshold was read.""")


class AnalysisVerdict(ConfiguredBaseModel):
    """
    pondie's verdict on one analysis of the parse a revision revises, reached while extracting the whole record. The verdict overrides the original's proposal.
    What a verdict does to what is stored against the analysis -- claims, their evidence, and users' votes on them:
    - accept, relabel: nothing moves. The key is unchanged, so everything stored against
      it applies to the revision as it stands.
    - split: everything is copied to each analysis in `replaced_by`. - merge: everything stored against each merged analysis is copied to the one
      analysis they merge into. Two copies of the same field with the same value become
      one claim; with different values they stay competing claims, resolved like any
      other.
    - omit: nothing is copied. - add: nothing to copy; the analysis is new.
    Every copy records the key and parse it was copied from, so a reviewer can tell a copied claim from one made against the revision. The revised parse and everything stored against it are kept, unchanged, as history: superseded rather than deleted, and left out of projections and studysets.
    """
    key: str = Field(default=..., description="""The revised parse's analysis key; for `add`, the new analysis's key in this revision.""")
    verdict: AuditVerdict = Field(default=...)
    replaced_by: Optional[list[str]] = Field(default=None, description="""The keys in this revision that take the analysis's place: itself for accept and relabel, the replacements for split and merge, none for omit.""")
    role: Optional[Union[CoordinateRole, str]] = Field(default=None, description="""For relabel, the role the points have instead.""")
    reason: str = Field(default=...)
    evidence: Optional[list[TextSpan]] = Field(default=None, description="""The sentences of the paper the verdict rests on.""")


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
ArtifactHeader.model_rebuild()
ArticleIdentifiers.model_rebuild()
Producer.model_rebuild()
InputRef.model_rebuild()
TextSpan.model_rebuild()
ParsedPaper.model_rebuild()
Bibliography.model_rebuild()
Reference.model_rebuild()
Citation.model_rebuild()
Correction.model_rebuild()
Supplement.model_rebuild()
Section.model_rebuild()
ParsedTable.model_rebuild()
TableRow.model_rebuild()
TableTriage.model_rebuild()
CoordinateParse.model_rebuild()
ParsedAnalysis.model_rebuild()
CellRef.model_rebuild()
TableReading.model_rebuild()
OmittedAnalysis.model_rebuild()
TextSweep.model_rebuild()
SignSplit.model_rebuild()
ParsedPoint.model_rebuild()
PointValue.model_rebuild()
Threshold.model_rebuild()
AnalysisVerdict.model_rebuild()
