"""Small helpers for reading schemas with local LinkML imports."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

import yaml

#: Base class of every source-derived attribute in the extraction schema.
EXTRACTED_VALUE = "ExtractedValue"

#: The generated document-local identifier, which is never a cross-reference.
LOCAL_ID = "local_id"

#: LinkML's slot for subset membership, declared in neuroimaging-study-storage/subsets.yaml.
IN_SUBSET = "in_subset"


def own_attributes(classes: Mapping[str, object], class_name: str) -> dict[str, Mapping]:
    """Return a class's own attributes, ignoring anything it inherits."""

    definition = classes.get(class_name)
    if not isinstance(definition, Mapping):
        return {}
    attributes = definition.get("attributes") or {}
    if not isinstance(attributes, Mapping):
        return {}
    return {
        name: attribute
        for name, attribute in attributes.items()
        if isinstance(attribute, Mapping)
    }


def attribute_ranges(attribute: Mapping[str, object]) -> list[str]:
    """Every range an attribute can hold, in declaration order.

    A slot normally declares one `range`. A slot that accepts either a controlled
    value or free text declares neither, and instead lists both alternatives under
    `any_of` -- `any_of: [{range: SpatialScope}, {range: string}]`. Callers that
    reason about ranges have to see through that, or the enum branch becomes
    invisible: the MVP generator collects enums by range, so an unseen branch means
    an enum that the generated schema references but never defines.
    """

    declared = attribute.get("range")
    ranges = [declared] if isinstance(declared, str) else []
    alternatives = attribute.get("any_of")
    if isinstance(alternatives, Sequence) and not isinstance(alternatives, str):
        for alternative in alternatives:
            if isinstance(alternative, Mapping) and isinstance(alternative.get("range"), str):
                ranges.append(alternative["range"])
    return ranges


def is_marked(attribute: Mapping[str, object], subset: str) -> bool:
    """Whether an attribute declares membership in a subset."""

    declared = attribute.get(IN_SUBSET)
    if isinstance(declared, str):
        return declared == subset
    if isinstance(declared, Sequence):
        return subset in declared
    return False


def is_structural(attribute: Mapping[str, object]) -> bool:
    """Whether an attribute exists to hold the record together rather than to carry data.

    Identifiers and type designators are generated by the mapper, so no subset decision
    applies to them: a class cannot exist without them and no language model could supply
    them. Marking them anyway is harmless and some do it for the sake of an explicit
    inventory.
    """

    return attribute.get("identifier") is True or attribute.get("designates_type") is True


def is_selected(attribute: Mapping[str, object], subset: str) -> bool:
    """Whether an attribute belongs in a subset, by mark or by being structural."""

    return is_structural(attribute) or is_marked(attribute, subset)


def load_imported_classes(path: Path, key: str = "classes") -> dict[str, object]:
    """Return the merged definitions from a schema's local imports.

    `key` selects which top-level section to merge -- "classes" by default, "enums" to
    collect the vocabularies the same way.
    """

    classes: dict[str, object] = {}
    visited: set[Path] = set()

    def visit(schema_path: Path) -> None:
        schema_path = schema_path.resolve()
        if schema_path in visited:
            return
        visited.add(schema_path)

        with schema_path.open(encoding="utf-8") as stream:
            schema = yaml.safe_load(stream)
        if not isinstance(schema, Mapping):
            raise ValueError(f"{schema_path.name} must contain a YAML mapping.")

        imports = schema.get("imports", ())
        if not isinstance(imports, list):
            raise ValueError(f"{schema_path.name} imports must be a list.")
        for import_name in imports:
            if not isinstance(import_name, str) or ":" in import_name:
                continue
            import_path = schema_path.parent / import_name
            if import_path.suffix != ".yaml":
                import_path = import_path.with_suffix(".yaml")
            if not import_path.is_file():
                raise FileNotFoundError(f"Local schema import does not exist: {import_path}")
            visit(import_path)

        schema_classes = schema.get(key, {})
        if not isinstance(schema_classes, Mapping):
            raise ValueError(f"{schema_path.name} {key} must be a mapping.")
        classes.update(schema_classes)

    visit(path)
    return classes


def attributes_for(
    classes: Mapping[str, object], class_name: str
) -> dict[str, Mapping[str, object]]:
    """Return a class's attributes, including those inherited via LinkML is_a."""

    collected: dict[str, Mapping[str, object]] = {}
    ancestry: list[Mapping[str, object]] = []
    current: str | None = class_name
    seen: set[str] = set()

    while current and current not in seen:
        seen.add(current)
        definition = classes.get(current)
        if not isinstance(definition, Mapping):
            break
        ancestry.append(definition)
        parent = definition.get("is_a")
        current = parent if isinstance(parent, str) else None

    # Walk root-first so a subclass overrides an inherited attribute rather than
    # being overwritten by it.
    for definition in reversed(ancestry):
        attributes = definition.get("attributes", {})
        if isinstance(attributes, Mapping):
            for name, attribute in attributes.items():
                if isinstance(attribute, Mapping):
                    collected[name] = attribute

        # slot_usage is how ExtractedString and friends narrow `value`.
        usage = definition.get("slot_usage", {})
        if isinstance(usage, Mapping):
            for name, override in usage.items():
                if isinstance(override, Mapping) and name in collected:
                    collected[name] = {**collected[name], **override}

    return collected


def resolves_to(classes: Mapping[str, object], class_name: str, ancestor: str) -> bool:
    """Return whether class_name is, or inherits from, ancestor."""

    current: str | None = class_name
    seen: set[str] = set()
    while current and current not in seen:
        if current == ancestor:
            return True
        seen.add(current)
        definition = classes.get(current)
        if not isinstance(definition, Mapping):
            return False
        parent = definition.get("is_a")
        current = parent if isinstance(parent, str) else None
    return False


def subclasses_of(classes: Mapping[str, object], class_name: str) -> set[str]:
    """Return every class that inherits from class_name, directly or transitively.

    A slot whose range is an abstract class holds an instance of one of its subclasses,
    so a consumer walking ranges has to follow this edge too: Analysis.details ranges on
    the abstract AnalysisDetails and never on AnalysisDetails itself.
    """

    return {
        candidate
        for candidate in classes
        if candidate != class_name and resolves_to(classes, candidate, class_name)
    }


def type_designator(classes: Mapping[str, object], class_name: str) -> str | None:
    """The slot naming the concrete subclass, for a class carrying a self-naming payload.

    Read off `designates_type: true` rather than listed, so a third such family costs
    nothing. `attributes_for` resolves inheritance, so a subclass answers with the same
    slot its base declares.
    """

    for name, attribute in (attributes_for(classes, class_name) or {}).items():
        if isinstance(attribute, Mapping) and attribute.get("designates_type") is True:
            return name
    return None


def designated_type(
    classes: Mapping[str, object], node: object, declared: str
) -> str:
    """The class a record says it is, or `declared` when it does not say.

    A walker that recurses on the declared range alone never reaches the fields that make
    a self-naming payload useful: `Analysis.details` ranges on the abstract
    AnalysisDetails, whose only attribute is the designator, while `seed_regions` is
    declared on ConnectivityDetails. Resolving here is what stops those slots being
    invisible to every schema-driven pass.

    Silent by design -- it answers with the declared class when the designator is absent,
    unparseable, unknown, or names something that is not a subclass. A caller that must
    report those cases checks them itself; a repair pass only needs the best available
    answer.
    """

    designator = type_designator(classes, declared)
    if designator is None or not isinstance(node, Mapping):
        return declared
    named = node.get(designator)
    if not isinstance(named, str) or named not in classes:
        return declared
    return named if resolves_to(classes, named, declared) else declared


def classify_slot(classes: Mapping[str, object], name: str, attribute: Mapping[str, object]) -> str:
    """Classify one attribute by how a reviewer must treat it.

    identifier -- the generated local_id; not reviewable.
    evidence   -- range resolves to ExtractedValue, so it carries value + evidence.
    nested     -- range is another class the record owns; recurse into it.
    reference  -- range is another class the record only points at, carried as that
                  class's local_id. Reviewable, but the schema records no evidence
                  for it.
    native     -- a plain scalar that is not source-derived, e.g. the
                  ExtractionMetadata and PaperSection pipeline fields. Not
                  reviewable: the schema header notes these "use native LinkML
                  types because they are not source-derived extraction values".

    Ownership separates nested from reference, and LinkML states it: an inlined slot
    holds the record, a plain one holds its identifier. This used to be read off the
    description, because the hand-written extraction schema declared every
    cross-reference as `range: string` and nothing but the prose ("local_id of the Task
    record...") told Analysis.tasks apart from ExtractionMetadata.extractor_model. Since
    the extraction schema became a projection of storage, a reference keeps its real
    range and the prose is no longer load-bearing.
    """

    if name == LOCAL_ID:
        return "identifier"

    attribute_range = attribute.get("range", "string")
    if not isinstance(attribute_range, str):
        return "native"

    if attribute_range in classes:
        if resolves_to(classes, attribute_range, EXTRACTED_VALUE):
            return "evidence"
        if attribute.get("inlined") is True or attribute.get("inlined_as_list") is True:
            return "nested"
        return "reference"

    return "native"


def reference_slots(classes: Mapping[str, object]) -> dict[str, set[str]]:
    """Map each class name to the set of its local_id cross-reference slots."""

    return {
        class_name: {
            name
            for name, attribute in attributes_for(classes, class_name).items()
            if classify_slot(classes, name, attribute) == "reference"
        }
        for class_name in classes
    }

class _NotReported:
    """A slot the paper did not report: a claim, not an absence.

    Falsy, empty as a string and empty when iterated, so a caller that only wants the words
    is unaffected; identifiable by `is NOT_REPORTED` so a caller that must tell it from an
    absent slot, or from a slot the paper reported as empty, still can. It is not replaced by
    `[]` on a multivalued slot, because "did not say" and "said none" are different claims and
    collapsing them is the error this accessor exists to prevent.
    """

    __slots__ = ()

    def __bool__(self) -> bool:
        return False

    def __str__(self) -> str:
        return ""

    def __iter__(self):
        return iter(())

    def __len__(self) -> int:
        return 0

    def __repr__(self) -> str:
        return "NOT_REPORTED"


#: The one instance; compare with `is`.
NOT_REPORTED = _NotReported()


def value_of(node: object, multivalued: bool = False) -> object:
    """The value inside an ExtractedValue wrapper, in the shape its slot declares.

    Reading a record by hand gets three cases wrong, and each is a silent wrong answer
    rather than an error:

      * a wrapper with no `value` key is `not_reported` -- a positive claim that the paper
        did not say. Returning the wrapper makes it look like a scalar value.
      * a `multivalued` slot holds a list. A caller that takes the value as a scalar drops
        every entry but reads as if it succeeded.
      * an absent slot and a reported-empty slot are different; only the latter is a claim.

    `multivalued` comes from the schema -- see `slot_value` -- and is not guessed from
    whether this particular record happens to hold a list.
    """
    if node is None:
        return [] if multivalued else None
    if isinstance(node, Mapping):
        if "value" not in node:
            return NOT_REPORTED
        value = node["value"]
    else:
        value = node
    if multivalued:
        if isinstance(value, list):
            return value
        return [] if value is None else [value]
    return value


def slot_value(classes: Mapping[str, object], class_name: str, entity: Mapping[str, object],
               slot: str) -> object:
    """`value_of` with the slot's shape taken from the schema rather than from the caller."""
    attribute = own_attributes(classes, class_name).get(slot) or {}
    return value_of(entity.get(slot), bool(attribute.get("multivalued")))
