#!/usr/bin/env python3
"""The review layer's registry: what is asked, where it is asked, and what it is called.

Everything else in this package reads this file and restates none of it. The
config generator learns which blocks a project carries, the exporter learns each
task's stage and address, the deployer learns titles, overlap and Data Manager
views, the decoder learns how to read a control name back, and the chat backend
learns the two control names it writes to.

That is the whole design rule here. The previous layer kept six copies of this
information -- one per script -- and they drifted: the per-family overlap was
written down twice under a comment claiming it was derived once, and a Data
Manager view was created for a task kind that no longer existed.

## One project per task kind family, never one per paper

A Label Studio project holds exactly one labeling config (`projects/models.py:198`)
and one `maximum_annotations` (`:259`). Splitting by task kind is what lets each
family carry its own UI *and* its own reviewer overlap. Papers are grouped by a
Data Manager view on `data.paper_id`; see `task-organization.md` for the
alternatives and why they lose.

## Every block is gated, including the ones that did not need to be

A `Repeater` is expanded client-side against the task's own data, and an absent
or empty key yields zero copies (`core/Tree.tsx:70-73`). So a block wrapped in
`<Repeater on="$gate_model">` renders only for a task carrying that key, and a
`required="true"` control inside it is never instantiated for any other kind and
cannot block their submission.

Every kind uses that mechanism, even the projects holding a single kind. The
uniformity is the point: "exactly one required question per task" becomes a
structural property rather than a coincidence, and one expansion, one decoder and
one sample-task builder serve all seven variants.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

#: The one object tag. Every control points at it, every span is drawn on it, and
#: the chat backend hardcodes it as the `to_name` of its reply -- a suggestion
#: naming any other tag is dropped without a message.
PAPER = "paper"

#: The two ends of Label Studio's interactive-preannotation round trip. `chat.py`
#: imports these rather than restating them: a rename on one side alone is silent,
#: because the backend would answer a question it never sees and write into a
#: control that does not exist.
CHAT_QUESTION = "chat_q"
CHAT_ANSWER = "chat_a"

#: Where staged paper texts live under the files root, and how Label Studio serves
#: them. `chat.py` reads the same tree to answer questions about the open paper.
TEXT_SUBDIR = "texts"
LOCAL_FILES_URL = "/data/local-files/?d={relative}"

#: Task-data keys the chat backend does not put in front of the model. Everything
#: else is sent, whatever shape it has -- for four of the seven kinds the object
#: under review IS an array, and a filter that kept only short scalars once left a
#: contrast task telling the model nothing but a paper id and the word "contrast".
#:
#:   paper_url                 the text is sent whole; the URL is plumbing
#:   content_hash, review_key  addresses, not content
#:   paper_text_hash           the same
#:   labels, columns           the span chips and the grid headers, whose
#:                             descriptors the rendered rows already carry
#:   legend                    the inventory table; `rows` is the same data
#:   table_html                the one entry here that is not plumbing. It is the
#:                             object under review on a contrast task, and it is
#:                             skipped because a rendered grid runs to ~20 KB of
#:                             markup -- 255 KB across one paper's contrast tasks --
#:                             which would be pasted into every chat turn in the
#:                             project. The same table reaches the model in readable
#:                             form through `rows` and the gate's `meta`.
#:
#: A key not named here is sent even if it is unrecognised: an exporter that grows
#: a field should reach the model by default and be excluded on purpose.
CHAT_SKIP_KEYS = frozenset({
    "paper_url", "content_hash", "review_key", "paper_text_hash",
    "labels", "columns", "legend", "table_html",
})

#: One index flag per nesting depth. `{{idx}}` substitution is `String.replace`
#: with a string pattern (`core/Tree.tsx:48`), so only the first occurrence in an
#: attribute is replaced and nested Repeaters must not share a flag. Fixing the
#: flags by depth means no block has to invent a spelling, and a name carries its
#: whole address: `model_level_0_2_1` is level 1 of term 2.
FLAGS = ("{{i}}", "{{j}}", "{{k}}")


# -- the control-name grammar ----------------------------------------------
#
# `<kind>_<role>` plus one index per enclosing Repeater. Generated by `control`,
# read back by `parse_control`, and that is the only reason answers can be decoded
# at all: Label Studio stores `from_name`, so the name has to carry the address.
#
# Kind and role are lowercase letters only, which is what makes the split
# unambiguous -- everything after the second underscore is an index.

_CONTROL = re.compile(r"^(?P<kind>[a-z]+)_(?P<role>[a-z]+)(?P<indices>(?:_\d+)*)$")


def gate(kind: str) -> str:
    """The task-data key whose presence renders this kind's block."""

    return f"gate_{kind}"


def control(kind: str, role: str, depth: int = 1) -> str:
    """A control name carrying one index flag per enclosing Repeater.

    `depth` counts the Repeaters the control sits inside. It is never zero: every
    block is gated, so the gate's own flag is always present and always resolves
    to 0 -- which is what lets a `whenTagName` inside a block name a control
    declared in the same block without hardcoding an index.
    """

    if not kind.isalpha() or not role.isalpha():
        raise ValueError(
            f"control names split on underscores, so kind and role must be letters "
            f"only; got {kind!r}, {role!r}"
        )
    if not 1 <= depth <= len(FLAGS):
        raise ValueError(f"depth must be 1..{len(FLAGS)}, got {depth}")
    return "_".join([kind, role, *FLAGS[:depth]])


def instance(kind: str, role: str, *indices: int) -> str:
    """The name a control ends up with once the editor has expanded the Repeaters.

    The gate's index is always 0, because a gate array holds exactly one element;
    anything after it addresses a row. Predictions are written against these names
    and answers are read back from them, so this and `control` have to agree --
    which is why they are three lines apart.
    """

    return "_".join([kind, role, "0", *(str(index) for index in indices)])


@dataclass(frozen=True)
class Control:
    """A parsed control name: which question, about which row."""

    kind: str
    role: str
    indices: tuple[int, ...]

    @property
    def row(self) -> int | None:
        """The row this control addresses, or None for a block-level control.

        Index 0 is the gate's, which is always 0 and never addresses anything.
        """

        return self.indices[1] if len(self.indices) > 1 else None


def parse_control(name: str) -> Control | None:
    """Read a stored `from_name` back into (kind, role, indices).

    Returns None for anything this grammar did not generate -- `comment`, the
    object tag, and the chat controls, whose `chat_q` reads as a kind and a role
    until the kind is checked against the register. Checking it there is what keeps
    the decoder from needing a list of exceptions to skip.
    """

    match = _CONTROL.match(name or "")
    if not match or match.group("kind") not in BY_NAME:
        return None
    indices = match.group("indices")
    return Control(
        kind=match.group("kind"),
        role=match.group("role"),
        indices=tuple(int(part) for part in indices.split("_")[1:]) if indices else (),
    )


# -- verdict vocabularies ---------------------------------------------------
#
# Every entry names the failure it is for. A vocabulary of correct/wrong pushes
# the diagnosis into free text, where nothing can count it.

Vocabulary = tuple[tuple[str, str], ...]

FIELD_VERDICTS: Vocabulary = (
    ("correct", "Value and evidence are both right (or correctly marked not reported)"),
    ("wrong_value", "Evidence points at the right passage but the value is wrong"),
    ("wrong_evidence", "Value is right but the evidence does not support it"),
    ("wrong_both", "Neither the value nor the evidence is right"),
    ("should_be_not_reported", "The paper does not report this; the extractor invented a value"),
    ("missed_value", "Marked not reported, but the paper does state it"),
    ("uncertain", "Cannot determine from the paper"),
)

#: Generic over classes, because "did the extractor find the right set of these?"
#: is one question with one shape. This is stage 0: every other family addresses
#: objects by `local_id`, so a wrong instance set is the one correction that
#: invalidates work everywhere else.
INVENTORY_VERDICTS: Vocabulary = (
    ("inventory_correct", "The right instances, and no others, were extracted"),
    ("instance_missing", "The paper describes one that is not here"),
    ("instance_spurious", "One here is not a real instance of this class"),
    ("duplicates_present", "Two rows are the same thing"),
    ("should_split", "One row covers two distinct things"),
    ("uncertain", "Cannot determine from the paper"),
)

MODEL_VERDICTS: Vocabulary = (
    ("terms_correct", "The term list and its levels are right"),
    ("term_missing", "The paper states a term this model does not list"),
    ("term_spurious", "A term here is not real -- mark which below to drop it"),
    ("term_wrong", "A term's name, type or scope is wrong -- fix it below"),
    ("levels_wrong", "A factor's levels are wrong or incomplete"),
    # Stages are advisory, so a reviewer who reaches this out of order must be
    # able to park the task rather than invent a repair stage 0 will undo.
    # Every downstream family needs this escape; this one was missing it.
    ("upstream_wrong", "This model should not exist in this shape -- see the inventory task"),
    ("uncertain", "Cannot determine from the paper"),
)

TABLE_VERDICTS: Vocabulary = (
    ("segmentation_correct",
     "Each analysis drawn from this table is one real analysis, and none is missing"),
    ("over_split", "One analysis was split into two or more"),
    ("merged", "Two analyses were recorded as one"),
    ("missed_analysis", "The table reports an analysis the parser did not find"),
    ("wrong_rows", "The split is right, but a row is attributed to the wrong analysis"),
    ("not_analyses",
     "This table reports no analysis -- demographics, an ROI definition, a stimulus list"),
    ("uncertain", "Cannot determine from the table and the paper"),
)

CONTRAST_VERDICTS: Vocabulary = (
    ("accept", "The record says what the paper says"),
    ("direction_wrong", "Right terms, wrong sides"),
    ("wrong_axis", "The comparison is on the wrong term"),
    ("cells_wrong", "A cell is missing, or one is here that should not be"),
    ("statistic_wrong", "The statistic or its degrees of freedom are wrong"),
    ("upstream_wrong", "This analysis should not exist in this shape -- see the inventory task"),
    ("uncertain", "Cannot determine from the paper"),
)

RESOLUTIONS: Vocabulary = (
    ("take_left", "Reviewer A is right"),
    ("take_right", "Reviewer B is right"),
    ("synthesize", "Neither is wholly right -- the corrected form is below"),
    ("escalate", "Needs a domain decision beyond this task"),
)

#: Per-instance dispositions, which map onto the propagation rules exactly.
#: `rename` and `merge` are a rewrite map that `build_record.apply_aliases` applies
#: to reference slots only, mechanically and completely. `drop` and `split` have no
#: target to rewrite to, so every reference to that instance is also wrong and its
#: downstream tasks are regenerated rather than fixed. The hints say which is which,
#: so a reviewer knows `drop` costs downstream work and `merge` does not.
DISPOSITIONS: Vocabulary = (
    ("keep", "A real, distinct instance"),
    ("rename", "Right instance, wrong label -- propagates as a rewrite"),
    ("merge", "Same thing as another row -- name it below; propagates as a rewrite"),
    ("drop", "Not a real instance; every reference to it needs re-review"),
    ("split", "Two things recorded as one; every reference to it needs re-review"),
)

#: The same shape for a parsed analysis: without it a reviewer can say "one of
#: these is two analyses" and has nowhere to say which one.
ANALYSIS_DISPOSITIONS: Vocabulary = (
    ("keep", "A real, whole analysis"),
    ("split", "Two analyses recorded as one -- every task drawn from it needs re-review"),
    ("merge", "The same analysis as another row -- name it below"),
    ("drop", "Not an analysis -- every task drawn from it needs re-review"),
    ("rows_wrong", "Right analysis, wrong rows attributed to it"),
)

TERM_VERDICTS: Vocabulary = (
    ("correct", "This term is right as recorded"),
    ("wrong_name", "The name misdescribes the term"),
    ("wrong_type", "Categorical vs continuous is wrong"),
    ("wrong_variation_level", "Within- vs between-subject is wrong"),
    ("should_be_two_terms", "This is two terms recorded as one"),
    ("duplicate_of_another_term", "Another term in this model is the same term"),
    ("not_a_term_of_this_model", "The model does not contain this term -- drops it"),
    ("spurious_interaction", "interaction_with is set on a crossing the cells already state"),
)

TERM_TYPES: Vocabulary = (
    ("categorical", "Declares levels"),
    ("continuous", "A slope or product column; declares no levels"),
)

VARIATION_LEVELS: Vocabulary = (
    ("within_subject", "Moves within a participant, like a repeated-measures factor"),
    ("between_subject", "Moves only across the sample, like a diagnosis or an age covariate"),
    ("both", "Moves both within and across participants"),
    ("unstated", "The paper does not say"),
)

#: How a cell weights its term. `unstated` and `not_applicable` are here because
#: the schema's own enum has them and the record uses them: both F-test main
#: effects in the baseline corpus carry `direction: unstated`, and a grid offering
#: only the three signed options rendered an omnibus test as "every term adjusted
#: for, none tested" -- the opposite of what the paper reports.
DIRECTIONS: Vocabulary = (
    ("positive", "Weighted positively, or a positive fitted coefficient"),
    ("negative", "Weighted negatively, or the lesser side of the comparison"),
    ("absent", "Not in this contrast -- adjusted for, or a zero weight"),
    ("unstated", "Tested, but the record does not say which way -- an omnibus F, say"),
    ("not_applicable", "The question does not arise for this term"),
)

#: Offered per task rather than as a fixed set: the exporter drops any option whose
#: subject the record does not hold. No analysis across the baseline papers records
#: degrees of freedom, so a fixed `df_wrong` asked every reviewer about a value that
#: was never there. `df_absent` is the half that *is* answerable when the record has
#: none, because it asks about the paper rather than the record.
STATISTIC_VERDICTS: dict[str, str] = {
    "statistic_correct": "Right as recorded",
    "family_wrong": "The wrong statistic family",
    "df_wrong": "The degrees of freedom are wrong",
    "df_absent": "The paper reports degrees of freedom the record omits",
}

#: How a highlighted passage relates to the value, judged per span while drawing
#: it. Not the same axis as `ValueSource`, which is a property of the value
#: (`reported` vs `generated`) rather than of the passage: a value the extractor
#: composed can still have a passage that states it outright.
SUPPORT_KINDS: Vocabulary = (
    ("direct support", "The passage states the value"),
    ("inferred support", "The value follows from the passage but is not stated in it"),
)

#: Distinct hues so co-existing span labels are separable at a glance. Hardcoded
#: rather than tokenised because Label Studio manages the text contrast of span
#: highlights itself -- these are the one exception to the tokens-only rule the
#: stylesheet otherwise holds to.
PALETTE = ("#ff9800", "#03a9f4", "#8bc34a", "#e91e63", "#9c27b0", "#795548")

#: One tint per analysis on a rendered coordinate table, as (fill, text, rule)
#: token triples. The renderer cycles through these and the stylesheet writes one
#: rule per entry, so the count is read from here by both rather than restated --
#: the previous pair drifted by a hardcoded `tints=4` against three rules.
#:
#: Three, and none of them red. Label Studio ships four chromatic semantic
#: families and the fourth is `negative`; an analysis is not an error for being
#: the fourth in its table. Past the third the tint cycles, and the gutter's
#: number -- not the colour -- is what tells the fourth analysis from the first.
#: The colour is a scanning aid; the number is the identity.
#:
#: The `-background` family rather than `-surface`: a `-surface` fill is saturated
#: enough that a coordinate printed on it is harder to read than the coordinate
#: beside it, and a table task tints every row.
TINTS: tuple[tuple[str, str, str], ...] = (
    ("--color-primary-background", "--color-neutral-content", "--color-primary-border"),
    ("--color-positive-background", "--color-neutral-content", "--color-positive-border"),
    ("--color-warning-background", "--color-neutral-content", "--color-warning-border"),
)

#: How many question/answer pairs the chat pane interleaves by position. CSS has
#: no arithmetic on `order`, so a pair costs two written-out rules and the count is
#: fixed at generation time. Well past what a reviewer asks about one field --
#: the busiest task in the first real run had four -- and anything beyond it still
#: renders, below the paired entries and above the typing bar.
CHAT_TURNS = 25


# -- whose predictions are whose --------------------------------------------


def model_version(model: str, version: str) -> str:
    """The `model_version` the exporter stamps on every prediction it writes."""

    return f"{model or 'unknown'}@{version or 'unknown'}"


def ours(stamp: str | None) -> bool:
    """Was this prediction produced by the extraction pipeline?

    The sync deletes predictions before rewriting them, so it needs to know which
    rows are its to remove: this instance's chat backend attaches one of its own to
    every task it answers, and deleting those would destroy the exchange the
    annotation is supposed to carry.

    Identity deliberately ignores *which* model did the extracting. Matching the
    exported stamp exactly meant that re-running the extractor under a different
    model made every live prediction unrecognisable -- the stale rows were kept as
    another producer's, the new ones written beside them, and each task ended up
    with two sets of spans at two different sets of offsets.

    So the rule is the separator, and the reciprocal obligation is on `chat.py`:
    its own stamp must never contain one.
    """

    return "@" in (stamp or "")


# -- when the correction editor opens ---------------------------------------


@dataclass(frozen=True)
class Editor:
    """The visibility rule on a block's correction form.

    Every config leads with the cheap judgement: show the whole object, ask one
    question, and keep the editor shut until the answer is not "correct". At 35-50
    entities and 5-9 analyses a paper, a reviewer who must fill a form for every
    task will not finish.

    `visibleWhen` reads only choices and regions, never task data
    (`tags/visual/View.jsx:62-65`), so this is the only conditional available.
    """

    #: "unless" hides the editor while the verdict is one of `values`;
    #: "when" shows it only once the verdict is one of them;
    #: "always" declares no gate at all.
    mode: str
    values: tuple[str, ...] = ()

    @property
    def visible_when(self) -> str:
        return {"unless": "choice-unselected", "when": "choice-selected"}[self.mode]


ALWAYS = Editor("always")


# -- Data Manager views -----------------------------------------------------
#
# The Data Manager's filter operators, as its store declares them (`dm/src/stores/
# Filters/*`, the union `store.js:490` parses a saved view against). There is no
# "one of a set" operator for a string column: `in` is a numeric or date RANGE
# taking {min, max}.
#
# The operator is checked here because the server does not check it at all. A view
# carrying an unknown one is stored with HTTP 201 and only fails in the browser,
# where mobx-state-tree cannot match it against the union and throws during Data
# Manager init -- before any view is selected, so ONE bad filter in ONE view hangs
# the whole project's Data Manager on the loading animation with nothing in the
# server log. `in_list` shipped that way and took the structure project down.

OPERATORS = frozenset({
    "equal", "not_equal", "less", "greater", "less_or_equal", "greater_or_equal",
    "in", "not_in", "empty", "contains", "not_contains", "regex",
})


@dataclass(frozen=True)
class Filter:
    key: str
    operator: str
    value: Any
    type: str = "String"

    def __post_init__(self) -> None:
        if self.operator not in OPERATORS:
            raise ValueError(
                f"{self.operator!r} is not a Data Manager operator, and a view carrying "
                f"it would be accepted by the server and then break the project's Data "
                f"Manager in the browser. Use one of: {', '.join(sorted(OPERATORS))}"
            )

    def as_payload(self) -> dict[str, Any]:
        """Column format per `data_manager/serializers.py:156`."""

        return {
            "filter": f"filter:tasks:data.{self.key}",
            "operator": self.operator,
            "type": self.type,
            "value": self.value,
        }


@dataclass(frozen=True)
class View:
    title: str
    filters: tuple[Filter, ...] = ()
    columns: tuple[str, ...] = ()


#: Coordinate-bearing is the default, not a tab: an object no reported result
#: rests on is deprioritised, never hidden. Split on `yes` rather than enumerating
#: the negatives, both because there is no set-membership operator and because
#: naming only the positive keeps this from going stale as the negative vocabulary
#: grows.
BEARING = Filter("coordinate_status", "equal", "yes")
UNRELATED = Filter("coordinate_status", "not_equal", "yes")


# -- the task kinds ---------------------------------------------------------


@dataclass(frozen=True)
class Kind:
    """One judgement, asked one way.

    `name` is the gate key's suffix, the `task_kind` written into task data, the
    prefix of every control the block declares, and the segment of the review key
    -- one string, four uses, so a kind cannot half-exist.
    """

    name: str
    #: Which correction a wrong answer here can invalidate, and therefore which
    #: round it is imported in. Derived rather than chosen: 0 changes nodes and
    #: invalidates everything below, 1 changes edges or leaves, 2 reads both.
    #: See `staged-validation.md`.
    stage: int
    #: The one required question. Empty means the kind declares no verdict, which
    #: only `relationship` does -- its grid arrives pre-ticked from the extraction,
    #: so the ticks are the answer and a verdict could only ask the reviewer to
    #: restate them. Everywhere else a task can be submitted untouched, and the
    #: verdict is what separates "checked and correct" from "never looked at".
    question: str
    verdicts: Vocabulary
    editor: Editor
    #: Standing instruction, identical for every task of this kind, so it is baked
    #: into the config rather than shipped on every task. It was task data once,
    #: and every task of a family carried the same three sentences.
    guidance: str = ""
    #: The prompt above the span layer. Empty declares no layer, which only
    #: `adjudication` does -- it judges two readings, not the paper.
    span_prompt: str = ""
    #: Whether the span layer lets a reviewer name something that is not in the
    #: record. True for the kinds whose subject is an inventory of objects, so a
    #: missing Group, term or analysis is reported the same way: draw the span,
    #: pick from the list or type a name, and the object is born attached to its
    #: evidence. Deliberately off for `relationship` -- "this links to something
    #: that was never extracted" is stage 0's question, and a second route to one
    #: correction means two places to reconcile.
    naming: bool = False
    #: Heading over the per-row correction form, if the kind has one.
    rows: str = ""

    @property
    def gate(self) -> str:
        return gate(self.name)

    @property
    def verdict(self) -> str:
        return control(self.name, "verdict")

    def named(self, role: str, depth: int = 1) -> str:
        return control(self.name, role, depth)


KINDS: tuple[Kind, ...] = (
    Kind(
        name="value",
        stage=1,
        question="Is this right?",
        verdicts=FIELD_VERDICTS,
        editor=Editor("unless", ("correct",)),
        span_prompt="Where this value appears",
    ),
    Kind(
        name="relationship",
        stage=1,
        question="",
        verdicts=(),
        editor=ALWAYS,
        span_prompt="Where these links are stated",
    ),
    Kind(
        name="entities",
        stage=0,
        question="Is this the right set of instances?",
        verdicts=INVENTORY_VERDICTS,
        editor=Editor("unless", ("inventory_correct",)),
        guidance=(
            "Judge the **set**, not the fields. Is each row a real, distinct "
            "instance of this class, and does the paper describe one that is not "
            "here? What each row *says* is reviewed field by field elsewhere.\n\n"
            "To report a missing one, highlight the passage that describes it and "
            "type its name."
        ),
        span_prompt="Where each instance appears, and any the record is missing",
        naming=True,
        rows="Disposition",
    ),
    Kind(
        name="model",
        stage=2,
        question="Is this the right term list?",
        verdicts=MODEL_VERDICTS,
        # The term list is NOT hidden behind the verdict. Answering `terms_correct`
        # would hide the very thing being called correct, and unlike a contrast --
        # whose cells are restated in its paraphrase -- a model's terms appear
        # nowhere else on the task. The accordion keeps each to one line instead.
        editor=ALWAYS,
        guidance=(
            "The list is this model's terms **and** the terms of any stage it was "
            "fitted on, because a contrast taken from the group stage can cell a "
            "first-level column. A covariate adjusted for is still a term; a level "
            "is a value a categorical term takes.\n\n"
            "To report a missing term, highlight the passage that states it and "
            "type its name."
        ),
        span_prompt="Where each term appears, and any the record is missing",
        naming=True,
        rows="Terms",
    ),
    Kind(
        name="table",
        stage=0,
        question="Is this the right set of analyses?",
        verdicts=TABLE_VERDICTS,
        editor=Editor("unless", ("segmentation_correct",)),
        guidance=(
            "Judge the **split**, not the encoding. Is each numbered block one real "
            "analysis, and does the table report one this list misses? How each is "
            "encoded is reviewed separately.\n\n"
            "To report a missed analysis, highlight where it is described and type "
            "its name."
        ),
        span_prompt="Where each analysis is described, and any the parse missed",
        naming=True,
        rows="Disposition",
    ),
    Kind(
        name="contrast",
        stage=2,
        question="Does the record say what the paper says?",
        verdicts=CONTRAST_VERDICTS,
        editor=Editor("unless", ("accept",)),
        span_prompt="Where this contrast is reported",
        rows="Direction per term",
    ),
    Kind(
        name="adjudication",
        stage=3,
        question="Which reading is right?",
        verdicts=RESOLUTIONS,
        editor=Editor("when", ("synthesize", "escalate")),
    ),
)

BY_NAME: dict[str, Kind] = {kind.name: kind for kind in KINDS}


# -- the projects -----------------------------------------------------------


@dataclass(frozen=True)
class Project:
    """One labeling config, one overlap policy, one import queue.

    `name` names the config file (`<name>.xml`) and the exported task file
    (`<paper>.tasks_<name>.json`), so those two cannot drift from each other or
    from the project they belong to.
    """

    name: str
    title: str
    description: str
    #: `maximum_annotations`. Differs per family on purpose: the value family is
    #: ~95% of the volume and wants one reviewer plus a priority-0 second pass,
    #: while the structural families are 13-20 tasks a paper and are where a
    #: second opinion is informative. One project per family is what makes that
    #: choice available at all.
    overlap: int
    kinds: tuple[str, ...]
    #: Data Manager columns for this project's generated views.
    columns: tuple[str, ...]
    #: Whether the config renders the coordinate table above its blocks. Declared
    #: once for the whole project rather than per kind, and not optional: both of
    #: this project's kinds want it, and Label Studio records `table_html` as a
    #: HyperText data type the moment the config is saved, after which it admits
    #: only a string for that key -- on import and on the PATCH the sync issues. A
    #: key present on only one kind's tasks would fail the other's.
    grid: bool = False
    #: Views beyond the per-kind and coordinate-status ones every project gets.
    extra_views: tuple[View, ...] = field(default_factory=tuple)

    @property
    def config_file(self) -> str:
        return f"{self.name}.xml"

    @property
    def task_suffix(self) -> str:
        return f"tasks_{self.name}"

    def task_file(self, paper_id: str) -> str:
        return f"{paper_id}.{self.task_suffix}.json"

    @property
    def blocks(self) -> tuple[Kind, ...]:
        return tuple(BY_NAME[name] for name in self.kinds)


_PAPER_COLUMN = "tasks:data.paper_id"

PROJECTS: tuple[Project, ...] = (
    Project(
        name="value",
        title="ns-review-value",
        description=(
            "One task per field of one entity: the extracted value, its evidence "
            "highlighted in the paper, and one verdict naming the failure."
        ),
        overlap=1,
        kinds=("value",),
        columns=(_PAPER_COLUMN, "tasks:data.entity_class", "tasks:data.field_path"),
        extra_views=(
            View(
                "Priority 0 first",
                (BEARING, Filter("priority", "equal", 0, "Number")),
                (_PAPER_COLUMN, "tasks:data.entity_class", "tasks:data.local_id"),
            ),
            View(
                "Value with no evidence found",
                (BEARING, Filter("evidence_status", "equal", "not_found")),
                (_PAPER_COLUMN, "tasks:data.entity_class", "tasks:data.field_path"),
            ),
            View(
                "Marked not reported",
                (BEARING, Filter("llm_status", "equal", "not_reported")),
                (_PAPER_COLUMN, "tasks:data.entity_class", "tasks:data.field_path"),
            ),
        ),
    ),
    Project(
        name="relationship",
        title="ns-review-relationship",
        description=(
            "One task per association slot per paper. Rows are the source objects, "
            "columns the candidate targets, so an unused target is an empty column."
        ),
        overlap=1,
        kinds=("relationship",),
        columns=(_PAPER_COLUMN, "tasks:data.rel_slot"),
    ),
    Project(
        name="structure",
        title="ns-review-structure",
        description=(
            "Stage-0 instance inventories, one per class, and one task per "
            "ModelEstimation. Two kinds in one config, selected by the gate the "
            "task carries."
        ),
        overlap=2,
        kinds=("entities", "model"),
        columns=(_PAPER_COLUMN, "tasks:data.local_id", "tasks:data.row_count"),
    ),
    Project(
        name="contrast",
        title="ns-review-contrast",
        description=(
            "One task per coordinate table -- is this the right set of analyses? -- "
            "and one per Analysis -- does the record say what the paper says? Both "
            "over the rendered table the analyses were read off."
        ),
        overlap=2,
        kinds=("table", "contrast"),
        grid=True,
        columns=(
            _PAPER_COLUMN, "tasks:data.table_id", "tasks:data.local_id",
            "tasks:data.row_count",
        ),
        extra_views=(
            # The axis this project exists for: one table and everything drawn from
            # it. The segmentation task and the contrasts that depend on it are
            # answered together or not at all.
            View(
                "By table",
                (BEARING,),
                (_PAPER_COLUMN, "tasks:data.table_id", "tasks:data.task_kind",
                 "tasks:data.local_id"),
            ),
        ),
    ),
    Project(
        name="adjudication",
        title="ns-adjudication",
        description="Two reviewers' canonical forms side by side, and a resolution.",
        overlap=1,
        kinds=("adjudication",),
        columns=(_PAPER_COLUMN, "tasks:data.dispute_kind", "tasks:data.local_id"),
    ),
)

BY_PROJECT: dict[str, Project] = {project.name: project for project in PROJECTS}

#: Which project each kind is answered in.
PROJECT_OF: dict[str, Project] = {
    name: project for project in PROJECTS for name in project.kinds
}


def views(project: Project) -> list[View]:
    """The Data Manager views to create for a project, in tab order.

    Derived rather than hand-listed. A project opens on its coordinate-bearing
    queue; a project carrying several kinds gets one tab each so a reviewer can
    take one kind across papers; every project ends with the remainder, because an
    object no reported result rests on is deprioritised and never dropped.

    Per-paper views are added at deploy time from the tasks actually imported.
    """

    out = [View("All tasks", (BEARING,), project.columns)]
    if len(project.kinds) > 1:
        out += [
            View(
                f"{name.capitalize()} tasks",
                (BEARING, Filter("task_kind", "equal", name)),
                project.columns,
            )
            for name in project.kinds
        ]
    out += list(project.extra_views)
    out.append(View("No reported result rests on this", (UNRELATED,), project.columns))
    return out
