"""The contracts between the pipeline's repositories, generated from this repository's LinkML.

    study_schema.models.paper_parse   ParsedPaper, CoordinateParse   ingestion -> pondie, ingester
    study_schema.models.extraction    Study (an extraction record)   pondie -> ingester
    study_schema.models.storage       Study (the storage shape)      ingester -> neurostore
    study_schema.jsonschema           the same contracts as JSON Schema, for non-Python readers
    study_schema.layouts              where those files sit on disk (needs the `layouts` extra)

The models and JSON Schemas are generated by `tools/generate_models.py` and committed; the
YAML is the source and is never edited through them. Each model module carries the version
of the schema it was generated from as `version`.
"""

__version__ = "0.1.0"
