"""Build the Python package's models and JSON Schemas from the LinkML YAML.

The YAML is the contract; everything under `src/study_schema/models/` and
`src/study_schema/jsonschema/` is generated from it by this script and committed, so a
consumer installs the package without LinkML and CI can tell when the two disagree:

    python tools/generate_models.py           # rewrite the generated files
    python tools/generate_models.py --check   # exit 1 if any is out of date

One change is made on the way, to the extraction schema only, and it is the schema's own
stated intent. A slot such as `Group.arm` is declared `inlined: false`, which the README reads
as "resolved through the target's `local_id`" -- but LinkML can only resolve a reference
through a slot marked `identifier: true`, and `local_id` is not marked. Left alone, every
generator inlines the target, so the models demand a nested `Arm` where a record holds the
string `"arm-social-support"`. Here `local_id` is marked as the identifier of each class that
has one, which turns those slots into the plain string references the records hold. The fix
belongs upstream, in `pondie.schema.generate`'s projection of `id` to `local_id`; until it
lands there, this is the only place it is made.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "study_schema"


@dataclass(frozen=True)
class Contract:
    module: str
    schema: str
    #: JSON Schema file name -> top-level class.
    roots: dict[str, str]
    mark_local_ids: bool = False


CONTRACTS = (
    Contract(
        module="paper_parse",
        schema="neuroimaging-paper-parse.yaml",
        roots={
            "parsed-paper": "ParsedPaper",
            "coordinate-parse": "CoordinateParse",
        },
    ),
    Contract(
        module="extraction",
        schema="neuroimaging-study-extraction.yaml",
        roots={"extraction-record": "Study"},
        mark_local_ids=True,
    ),
    Contract(
        module="storage",
        schema="neuroimaging-study-storage.yaml",
        roots={"storage-study": "Study"},
    ),
)


def _header(contract: Contract) -> str:
    return (
        f"# Generated by tools/generate_models.py from {contract.schema}.\n"
        "# Do not edit: change the YAML and regenerate.\n"
    )


def _view(contract: Contract):
    from linkml_runtime.utils.schemaview import SchemaView

    view = SchemaView(str(ROOT / contract.schema))
    view.merge_imports()
    if contract.mark_local_ids:
        for cls in view.schema.classes.values():
            attribute = cls.attributes.get("local_id")
            if attribute is not None:
                attribute.identifier = True
    view.set_modified()
    return view


def render() -> dict[Path, str]:
    """Every generated file, path -> contents."""
    from linkml.generators.jsonschemagen import JsonSchemaGenerator
    from linkml.generators.pydanticgen import PydanticGenerator

    out: dict[Path, str] = {}
    for contract in CONTRACTS:
        view = _view(contract)
        models = PydanticGenerator(
            view.schema, extra_fields="forbid", metadata_mode=None
        ).serialize()
        out[PACKAGE / "models" / f"{contract.module}.py"] = _header(contract) + models
        for name, top in contract.roots.items():
            document = json.loads(
                JsonSchemaGenerator(_view(contract).schema, top_class=top).serialize()
            )
            out[PACKAGE / "jsonschema" / f"{name}.schema.json"] = (
                json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
            )
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if a generated file is out of date"
    )
    args = parser.parse_args(argv)

    stale = []
    for path, text in render().items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        stale.append(path)
        if args.check:
            diff = difflib.unified_diff(
                (current or "").splitlines(keepends=True),
                text.splitlines(keepends=True),
                fromfile=f"{path.relative_to(ROOT)} (committed)",
                tofile=f"{path.relative_to(ROOT)} (generated)",
                n=1,
            )
            sys.stdout.writelines(list(diff)[:40])
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)

    for path in stale:
        verb = "out of date" if args.check else "wrote"
        print(f"{verb}: {path.relative_to(ROOT)}")
    if args.check and stale:
        print("run: python tools/generate_models.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
